opstrace/opstrace

lib/gcp/src/iam.ts
lib/gcp/src/index.ts
lib/gcp/src/types.ts
lib/gcp/src/util.ts
packages/config/src/gke.ts
packages/controller-config/src/types.ts
packages/controller/src/resources/cortex/index.ts
packages/controller/src/resources/ingress/certManager.ts
packages/controller/src/resources/ingress/externalDns.ts
packages/controller/src/resources/loki/index.ts
packages/installer/src/gcp.ts
packages/installer/src/index.ts
packages/uninstaller/src/gcp.ts

The goal of this PR is to remove GCP credentials from the controller config map. 
In this PR we introduce functions that handle the creation and configuration of a GCP service account. We are using the `dns.admin` and `storage.admin` roles but we can follow up by reducing service account permissions to only the required roles.
To enable workload identity we need to provide [an additional parameter to the GKE cluster configuration](https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1/projects.locations.clusters).
Since we remove the GCP credentials we need to use a service account in the cert-manager, external-dns, cortex and loki deployments that access GCP cloud resources.
https://github.com/kubernetes-sigs/external-dns/blob/master/docs/tutorials/gke.md …

chore: enable GKE workload identity

---

ci/deploy-testremote-teardown.sh

From https://linux.die.net/man/1/bash
"The shell does not exit if the command that fails is part of the command list immediately following a while or until keyword..."
Fix #115

fix: no need to set/unset bash errexit

---

.gitignore
Makefile

This improves developer productivity (slightly) by reducing the compile time since we only need to run `yarn install` when a `package.json` or `yarn.lock` changed.

chore: prevent yarn install from running twice

---

.buildkite/pipeline.yml
.gitignore
Makefile
lib/kubernetes/jest.config.js
lib/kubernetes/package.json
lib/kubernetes/scripts/test.js
lib/kubernetes/src/equality/Certificate.spec.ts
lib/kubernetes/src/equality/Certificate.ts
lib/kubernetes/src/equality/index.ts
lib/kubernetes/src/reconciliation/reconcile.ts

Fix #43
When we add a new tenant, we need to check if the Certificate spec changed to trigger an update of the certificate resource in kubernetes. This will make cert-manager reconcile the resource and issue a new certificate with Let's Encrypt.

fix: update certificate resource when changes are made

---

lib/kubernetes/src/equality/Pod.ts
packages/controller/src/resources/apis/cortex.ts
packages/controller/src/resources/apis/loki.ts
packages/controller/src/resources/app/index.ts
packages/controller/src/resources/cortex/index.ts
packages/controller/src/resources/loki/index.ts
packages/controller/src/resources/monitoring/tenants/grafana.ts

Fix #131 
* Adds equality check for pod readiness and liveness probes. This required also setting the Kubernetes default values otherwise the desired spec and existing spec equality check would always fail.
* Adds liveness probes to the deployments/statefulsets/daemonsets that didn't have them.
* Changed `initialDelaySeconds` in cortex and loki deployments following the official helm chart values (for example, [cortex](https://github.com/cortexproject/cortex-helm-chart/blob/14ee59e7b3e8772f19a12ab16979e5143f51ae92/values.yaml#L250-L254)).

fix: set liveness and readiness probes

---

Makefile
packages/app/src/state/branch/hooks/__tests__/useBranches.test.tsx
packages/app/src/state/file/hooks/__tests__/useFiles.test.tsx
packages/app/src/state/module/hooks/__tests__/useModules.test.tsx
packages/app/src/state/moduleVersion/hooks/__tests__/useModuleVersions.test.tsx
packages/app/src/state/user/hooks/__tests__/useCurrentUser.test.tsx

Fix #139
* Adds missing license headers in source code files.
* Skips `.npm`, `.cache` and `build/` folders in license check to fix these kind of errors:
```
2020/12/09 10:47:53 ./.cache/yarn/v6/npm-is-accessor-descriptor-0.1.6-a9e12cb3ae8d876727eeef3843f8a0897b5c98d6-integrity/@(*.ts|*.tsx|*.json|*.go|*.css)
error: lstat ./.cache/yarn/v6/npm-is-accessor-descriptor-0.1.6-a9e12cb3ae8d876727eeef3843f8a0897b5c98d6-integrity/@(*.ts|*.tsx|*.json|*.go|*.css): no such file or directory
```

fix license check

---

.buildkite/pipeline.yml
Makefile
ci/preamble.sh

Close #135
*  Move all unit tests under a single makefile target
* Cleanup pipeline dependencies since unit-tests already depends on docs and preamble steps.

makefile: move all unit tests under a single target

---

lib/aws/src/bucket.ts
packages/installer/src/aws.ts

Adds a lifecycle rule to the S3 buckets used by loki and cortex to ensure data
is deleted periodically.
Things to know about when S3 data is deleted:
"Amazon S3 rounds the transition or expiration date of an object to midnight
UTC the next day. For example, if you created an object on 1/1/2020 10:30 UTC,
and you set the lifecycle rule to transition the object after 3 days, then the
transition date of the object is 1/5/2020 00:00 UTC. Before you check whether a
lifecycle rule has been satisfied, be sure to verify that enough time has
elapsed."

feat(aws): cortex/loki bucket lifecycle rule for data retention

---

docs/references/cluster-configuration.md

The tabs should be used here: both, `aws` and `gcp` are high-level optional configuration parameters that should be enumerated like all other high-level optional configuration parameters.
In addition to that, the tabbing leads to problems:
- notes and warnings are mixed
- the tab headings don't look great because of lower case letters (but lower case letters are correct, because that's how the parameters are named)

docs: remove aws/gcp tabs from cluster config ref

---

ci/check-if-docs-pr.sh

Close #161 
Output for PR where this issue was detected:
```
> BUILDKITE_PULL_REQUEST=160 bash ./ci/check-if-docs-pr.sh
+ source ci/utils.sh
+ echo 'BUILDKITE_PULL_REQUEST: 160'
BUILDKITE_PULL_REQUEST: 160
+ '[' -z 160 ']'
+ '[' 160 = false ']'
++ curl --silent -H 'Accept: application/vnd.github.v3+json' https://api.github.com/repos/opstrace/opstrace/pulls/160/files
++ command curl --connect-timeout 10 --retry 3 --retry-delay 5 --silent -H 'Accept: application/vnd.github.v3+json' https://api.github.com/repos/opstrace/opstrace/pulls/160/files
++ curl --connect-timeout 10 --retry 3 --retry-delay 5 --silent -H 'Accept: application/vnd.github.v3+json' https://api.github.com/repos/opstrace/opstrace/pulls/160/files
++ jq -r '.[].filename'
+ FILES_EDITED_IN_PR='.buildkite/pipeline.yml …
```

ci: fix docs pr check regex

---

lib/dns/src/opstrace.ts

We want to move to `got` and use established patterns, for good reasons :)
Until then...well.
Quick improvement for https://github.com/opstrace/opstrace/issues/187.
Also an explanation.
For more in-depth considerations, see commit msg.
I'd like to stress that this topic has bothered us before, by a _lot_. We initiated this conversation: https://github.com/eslint/eslint/issues/13567 -- which was super insightful for me.

chore: await axios.request()

---

.github/workflows/docs-sync.yml

Add a GitHub Action to re-index /docs with Algolia and re-deploy the website with the latest changes on `main`

docs: refresh algolia index and re-deploy website when docs change

---

packages/controller/src/resources/monitoring/tenants/prometheus.ts

Reduce the number of Prometheus scraping replicas. The proper fix will be by sharding the targets across Prometheus instances. This will be done in PR opstrace/opstrace#215.

fix: duplicate sample for timestamp

---

Makefile
ci/deploy-testremote-teardown.sh

For relaxing the pressure as of #62. Looks like the recent failures came from GCP project `ci-shard-aaa`. I finished setting up `ci-shard-ccc` for CI and propose to use projects ci-shard-bbb and ci-shard-ccc for the next couple of days.
We should investigate why we ran into quota issues within `ci-shard-aaa` -- I don't think an elevated build rate was responsible for that (recent days were pretty calm :christmas_tree:).

ci: gcp: use projects bbb and ccc for #62

---

Makefile
ci/data-collection-deployment-loop.sh
ci/metrics/prometheus.yaml.template
ci/metrics/promtail.yaml.template

* Deployed a new cluster from the latest main branch
* Deployed using a new AWS account to track costs
* Changed the name to `collection.opstrace.io`
* To save costs, changed instance type to t3a.xlarge

ci: upgrade collection cluster

---

lib/dns/src/opstrace.ts
lib/utils/src/httpclient.ts

Among others, this resolves issue #53.
```
When the DNS service responds to an HTTP
request with a 401 HTTP response then
this means that the authentication proof
(set of credentials) presented in the request
was invalid.
A common reason for that is authentication
proof / credential expiry. Therefore, a valuable
course of action is to obtain a fresh set of
credentials, by going through another login
process.
```
This also removes the last bits of usage of the Axios HTTP client in the installer/uninstaller (replaced with got) -- and therefore allows for closing #29.

Auth0 device code login (for DNS service authentication): consolidate (no axios, clearer polling loop, credential refresh, ...)

---

.markdownlint.json
docs/README.md
docs/guides/contributor/workflows.md
docs/guides/contributor/writing-docs.md
docs/guides/user/sending-logs-with-promtail.md
docs/quickstart.md
docs/references/faq.md
docs/references/roadmap.md
go.mod
yarn.lock

Fixes several broken links that were detected by a link check.
According to [the fluentd website](https://www.fluentd.org), it's `Fluentd`, not `FluentD`, which has been adjusted in the markdown linter config.

fix: broken links, adjust Fluentd name

---

.gitignore
go.mod

Let's remove go mod to avoid having it overwritten unnecessarily, for example, https://github.com/opstrace/opstrace/pull/251/files#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6R4-R8

chore: remove root go.mod

---

Makefile
ci/deploy-testremote-teardown.sh

CI has been broken all weekend (except for one successful build).  #254 did not work as initially expected.  Let's just create 3 new projects to immediately unblock us.
I followed [our instructions](https://opstrace.com/docs/guides/administrator/gcp-setup#step-1-create-a-project) for creating a new project and uploaded the credentials from step 6 to our CI bucket.
Note: these projects initially have the default 40 instance limit.  We may increase that to the max 100 later, or may keep it as-is.

ci(gcp): use brand new projects -ddd, -eee, -fff for CI

---

packages/controller/src/resources/storage/aws.ts
packages/controller/src/resources/storage/gcp.ts

This can be used in an emergency. For example, when the ingester volume reaches the default limit, this triggers a crash loop of that pod because it can't write to a full volume. Allowing the PVC to be resized makes it easier to address the issue proactively. 
[Kubernetes docs](https://kubernetes.io/docs/concepts/storage/persistent-volumes/)
[GCP docs](https://cloud.google.com/kubernetes-engine/docs/how-to/persistent-volumes/volume-expansion#using_volume_expansion) 
[AWS docs](https://kubernetes.io/docs/concepts/storage/storage-classes/#aws-ebs)

controller: allow pvc volume expansion

---

containers/controller/Dockerfile

`make build-and-push-controller-image` fails consistently with "JavaScript heap out of memory" on macOS Big Sur + Docker 3.0.4.

fix: increase available memory for node build

---

packages/controller-config/src/types.ts
packages/controller/package.json
packages/controller/src/resources/app/index.ts
packages/controller/src/resources/monitoring/tenants/grafana.ts
packages/installer/src/aws.ts
packages/installer/src/gcp.ts
packages/installer/src/index.ts
packages/installer/src/types.ts
yarn.lock

Before this PR grafana was still using sqlite in a volume.
This PR takes advantage of the aurora and cloudsql databases to fix that.

Grafana: use postgres db

---

packages/controller-config/src/docker-images.json

https://github.com/cortexproject/cortex/releases/tag/v1.7.0-rc.0
A few points that I found particularly itneresting:
>  Blocks storage: the default value of -blocks-storage.bucket-store.sync-interval has been changed from 5m to 15m
> Blocks storage: introduced a per-tenant bucket index, periodically updated by the compactor, used to avoid full bucket scanning done by queriers, store-gateways and rulers. The bucket index is updated by the compactor during blocks cleanup, on every -compactor.cleanup-interval. #3553 #3555 #3561 #3583 #3625 #3711 #3715
> Blocks storage: introduced an option -blocks-storage.bucket-store.bucket-index.enabled to enable the usage of the bucket index in the querier, store-gateway and ruler. When enabled, the querier, store-gateway and ruler will use the bucket …

bump: cortex 1.7.0-rc0

---

packages/cli/src/status.ts

`readTenantApiTokenFiles` was appending the `system` tenant to the input array. The other functions don't expect the system tenant to be in the input array.
Fix #296

cli: fix append to tenant names array

---

lib/kubernetes/src/utils/affinity.ts

Use `preferredDuringSchedulingIgnoredDuringExecution` instead of `requiredDuringSchedulingIgnoredDuringExecution`.
https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#affinity-and-anti-affinity
> You can think of them as "hard" and "soft" respectively, in the sense that the former specifies rules that must be met for a pod to be scheduled onto a node (just like nodeSelector but using a more expressive syntax), while the latter specifies preferences that the scheduler will try to enforce but will not guarantee. 
Fix #291
Using the "hard" setting `requiredDuringSchedulingIgnoredDuringExecution` prevents Kubernetes deployments from rolling out thereby preventing an upgrade from running.

controller: fix affinity rules

---

.gitignore
ci/check-if-docs-pr.sh
go/Makefile

* `md5sum` is not available on macos by default; use shasum as a cross-platform alternative
* also ignore local build artifacts

chore: make go build cross-platform

---

go/pkg/ddapi/translate.go

These changes are based on local testing / exploration. Also see code comments and https://github.com/opstrace/opstrace/issues/329.

DD API: be more liberal w.r.t. order of samples in request, keep interval as label

---

docs/guides/administrator/troubleshooting.md
docs/quickstart.md

As discussed, this PR adds a new section to the quickstart describing a workaround when the installation is stuck waiting for the certificate to be ready.

docs(quickstart): document workaround for known issue #151

---

go/cmd/graphql/README.md
go/cmd/graphql/main.go
go/pkg/graphql/credential.go
go/pkg/graphql/exporter.go

The graphql api service doesn't have a reverse proxy in front of it, instead we SHOULD accept the tenant name on startup.
I had misunderstood the existing controller code and thought there was a reverse proxy injecting the tenant name on requests.
Partial revert of commit 17916c497f7a4de2107ff576a52f777959cffadc.

graphql: Revert to accepting the tenant via commandline argument

---

Makefile

At the moment there are some build warnings that at first glance make it look like the build failed. This should help counter that impression when it isn't the case, while also giving a handy pointer to the build output.
Sample output:
```
+ yarn run pkg packages/cli/package.json --public --targets node14-linux-x64 --output build/bin/opstrace --options stack-trace-limit=100
yarn run v1.22.10
$ /home/nick/opstrace/opstrace/node_modules/.bin/pkg packages/cli/package.json --public --targets node14-linux-x64 --output build/bin/opstrace --options stack-trace-limit=100
> pkg@4.4.9
> Warning Cannot include file %1 into executable.
The file must be distributed with executable as %2.
%1: node_modules/open/xdg-open
%2: path-to-executable/xdg-open
> Warning Cannot include file %1 into executable. …
```

makefile: Print success message when build finishes

---

packages/controller-config/src/docker-images.json
packages/controller/src/resources/apis/config.ts
packages/controller/src/resources/apis/index.ts

This deploys the `config` service from `go/cmd/config/`. It serves endpoints for adding/updating/removing credentials and exporters in the GraphQL service. It is accessible at e.g. `config.cluster-name.opstrace.io`. The endpoints are currently documented in `go/cmd/config/README.md`, planning on writing a nice user-facing guide once the controller sync support is complete.
The controller deploys a single common `config` ingress/service/pod into the `application` namespace, rather than the per-tenant namespaces, so that it can use the existing Hasura access secrets in the `application` namespace. This felt like a better tradeoff than running instances in each of the tenant namespaces, which would have meant needing to add a copy of the Hasura secret into the per-tenant namespaces as well. …

controller: Add config API pod to application deployment

---

docs/guides/contributor/workflows.md

docs(workflows): add links to the guidance for applying copyright notices

---

Makefile
ci/test-upgrade/run.sh

Close #368 
* Adds test-remote-looker make target to run the looker tests
* Adds export statement in Makefile to set environment variables in scripts.

test-upgrade: run looker tests

---

ci/utils.sh

LE changed the issuer name of the certificate used to sign staging environment certificates on Feb 18: https://community.letsencrypt.org/t/staging-hierarchy-changes/145633
We check for this issuer name in CI to confirm that the certs exposed by API endpoints are indeed derived from
LE infrastructure. After the LE-internal naming change we have to update our check. See issue #386.

ci: cert check: update issuer grep text

---

test/test-remote/test_dd.ts

yolo-merging https://github.com/opstrace/opstrace/pull/394 was not a good idea. It introduced a new problem.
It's sad that there is no simple way to deactivate a test (like a 'marker').
Another pragmatic idea, returning early from a function, makes compilation fail.
Now I try outcommenting the entire test function. Hopefully this does not yield compilation errors.

test-remote: simpler test deactivation

---

lib/gcp/package.json
lib/gcp/src/cloudSQL.ts
yarn.lock

Breaking changes in the servicenetworking api were released in GCP. Bumping the library to latest `googleapis` version to see if that resolves the issue.
https://github.com/googleapis/google-api-nodejs-client/releases/tag/v66.0.0
fixes https://github.com/opstrace/opstrace/issues/293

Fix cloudsql instance creation

---

packages/controller-config/src/docker-images.json

Cortex 1.7.0-rc.2 was released about a day ago.
Since rc0, there have been two important fixes:
> [BUGFIX] Handle missing samples due to large steps and single point extents
> [BUGFIX] Fix ring tokens sorting regression introduced in #3601
https://github.com/cortexproject/cortex/releases

bump: cortex 1.7.0 rc0 -> rc2

---

package.json
packages/app/src/client/services/Picker/__tests__/PickerService.test.tsx
packages/app/src/state/user/__tests__/reducer.test.ts
yarn.lock

Unclear if these are just caused by my local environment or if something else is going on, but makes some quick fixes to fix regressions that I started seeing in the build yesterday:
`packages/app` build (via `yarn tsc -b`):
- Fix build errors around missing `toBeInTheDocument()`
- Fix build errors around missing fields in reducer tests
`packages/app` graphql generation (`yarn types:watch`):
- Fix runtime error around `looksLikeNumber is not a function`. Seems to be related to using an old yargs-parser version, see https://github.com/snowpackjs/snowpack/discussions/1468#discussioncomment-281258

ui: Build and graphql generation fixes - update deps and mock objects

---

ci/create-cluster-artifacts.sh
packages/config/src/gke.ts

PR for debugging and resolving #407
Tested manually with
```
± kubectl get all --namespace=system-tenant 2>/dev/null | awk '{print $1}' | \
>     grep 'pod/systemlog' | while read PNAME; do echo "get logs for $PNAME" | \
>     tee /dev/stderr ; kubectl logs $PNAME --namespace=system-tenant --all-containers=true; done \
>     > clusterlogs_fluentd-${OPSTRACE_CLUSTER_NAME}.log
get logs for pod/systemlog-cnjj2
get logs for pod/systemlog-jslcq
get logs for pod/systemlog-wpz69
```

ci: fetch fluentd logs with kubectl, switch to GKE REGULAR release channel (k8s 1.18)

---

containers/systemlog-fluentd/Dockerfile
packages/controller-config/src/docker-images.json

Log of building and pushing image:
```
$ make build-image
docker build -t opstrace/systemlog-fluentd:0798f0a-dev .
Sending build context to Docker daemon   7.68kB
Step 1/4 : FROM fluent/fluentd:v1.12.0-debian-1.0
---> 9c3c00d2a1d1
Step 2/4 : USER root
---> Using cache
---> 40a080b18123
Step 3/4 : RUN buildDeps="sudo make gcc g++ libc-dev git"    && apt-get update    && apt-get install -y --no-install-recommends $buildDeps    && oldpath=`pwd` && mkdir /tmp/lokicheckout && cd /tmp/lokicheckout    && git init && git remote add origin https://github.com/jgehrcke/loki    && git fetch origin 081cc024d67d0292a377f5995f4822a07a8e38af    && git reset --hard FETCH_HEAD    && cd /tmp/lokicheckout/cmd/fluentd/    && gem build fluent-plugin-grafana-loki.gemspec    && gem install --ignore-dependencies …
```

systemlogs: bump fluentd and plugins

---

packages/controller/src/resources/loki/index.ts

Analogue to https://github.com/opstrace/opstrace/pull/419.

loki: bump grpc msg size limits 10x

---

go/cmd/config/README.md
go/cmd/config/main.go
go/cmd/cortex/main.go
go/cmd/loki/main.go
go/pkg/middleware/authenticator.go
go/pkg/middleware/proxy.go
go/pkg/middleware/proxy_test.go
packages/app/config/swTemplate.js
packages/controller-config/src/docker-images.json
packages/controller/src/resources/apis/cortex.ts
packages/controller/src/resources/apis/index.ts
packages/controller/src/resources/apis/loki.ts
packages/controller/src/resources/app/api.ts
packages/controller/src/resources/app/app.ts
packages/controller/src/resources/app/index.ts
packages/controller/src/resources/cortex/index.ts
packages/controller/src/tasks/reconciliation.ts

- Updates application ingress to route `<cluster>/api/*` to the config-api pod (was: `config.<cluster>/api/*`)
- Moves cortex alertmanager and ruler APIs into the config-api pod
- Updates the config-api pod with alertmanager and ruler endpoints to be proxied
- Refactors auth and proxy handling a bit for reuse across services, while adding custom path override support when routing requests

controller: Update routes for config APIs (#379)

---

.buildkite/pipeline.yml
.buildkite/test-upgrade-pipeline.yml
lib/gcp/src/iam.ts
packages/cli/src/schemas.ts
packages/cli/src/util.ts
packages/controller-config/src/docker-images.json
packages/installer/src/gcp.ts
packages/uninstaller/src/gcp.ts

This also changes the cluster name pattern used by the various CI pipelines. Relevant commit msg:
```
This helps addressing #294.
This also gets rid of using the same cluster name
pattern as for everything else in the upgrade
tests -- where the only difference was that we
started off with lower sequential build numbers.
```

CLI / CI: test cluster name length limit of 23

---

packages/controller/src/resources/cortex/index.ts

https://cortexmetrics.io/docs/configuration/configuration-file/#blocks_storage_config
https://cortexmetrics.io/docs/blocks-storage/
About `block_ranges_period`:
> The in-memory samples are periodically flushed to disk - and the WAL truncated - when a new TSDB block is created, **which by default occurs every 2 hours**. 
About `retention_period`:
> Each newly created block is then uploaded to the long-term storage and kept in the ingester until the configured -blocks-storage.tsdb.retention-period expires, in order to give queriers and store-gateways enough time to discover the new block on the storage and download its index-header.
Powerful knobs, affecting fault tolerance, local disk usage, query performance, etc.

Cortex: explicit tsdb config, enable purger

---

packages/controller-config/src/docker-images.json

CI instability https://github.com/opstrace/opstrace/issues/432 motivated debugging, resulting in https://github.com/fluent/fluentd/pull/3274 and the corresponding patch https://github.com/fluent/fluentd/pull/3275. In the meantime, this reverts to the previously used systemlog docker container image.

systemlogs: revert fluentd bump (see #432)

---

lib/aws/src/bucket.ts
lib/gcp/src/bucket.ts
packages/controller-config/src/docker-images.json
packages/controller/src/resources/cortex/index.ts
packages/installer/src/aws.ts
packages/installer/src/gcp.ts
packages/uninstaller/src/aws.ts
packages/uninstaller/src/gcp.ts

UPGRADE-AFFECTING CHANGE: Adds a new `<cluster>-cortex-config` bucket, separate from the `<cluster>-cortex` bucket where metric data are stored. A separate config bucket is needed for multiple reasons:
- The cortex alertmanager and ruler currently only support writing configs when S3/GCS storage is being used (`configdb` store is effectively read-only).
- The main `<cluster>-cortex` bucket is configured with a TTL/expiration policy to automatically delete old files, which we do not want for alert/rule configs.
- The compactor separately automatically writes files to `/alerts/bucket-index.json.gz` and `/rules/bucket-index.json.gz`, which for alertmanager in particular causes fatal problems when it tries to scan configs.
- The alertmanager and ruler currently require storing data in …

alertmanager/ruler: ADD CONFIG BUCKET, get cortex alertmgr/ruler working (#430)

---

lib/kubernetes/package.json
yarn.lock

Fix #443 
First time bumping a single yarn dependency. This is what I did to update `package.json` and `yarn.lock`:
```bash
$ cd lib/kubernetes
$ yarn add @kubernetes/client-node@0.14.0
```

bump: kubernetes client-node to 0.14.0

---

packages/controller-config/src/docker-images.json

https://github.com/cortexproject/cortex/commit/a0c89bdf98e24ebfa4bf52a19cbd0bdc61a7b212
https://github.com/cortexproject/cortex/commit/68d537bc7f2d638f3f375ab673f6807338db5c1d
https://github.com/cortexproject/cortex/commit/d6d06693abaed36fd770c8f81799943f03d5da41
https://github.com/cortexproject/cortex/commit/f47690485631b8e5b62ea023e76770ac822042aa
https://github.com/cortexproject/cortex/commit/2b9453306534c40ee00ec533d6370bab4f459c88
https://github.com/cortexproject/cortex/commit/5dccf0829299a7f393b5c078fc5c6a7accd10d51
https://github.com/cortexproject/cortex/commit/5e496f428302a195a68cc287d97641561dbe0afd
>  Alertmanager: load alertmanager configurations from object storage concurrently, and only load necessary configurations, speeding configuration synchronization process and …

cortex: bump to current master

---

.buildkite/pipeline.yml
ci/wipe-bk-tmp-dir.sh

Fixes a concurrency issue where PREBUILD directory removal was invoked before unit-test ci step completion.
See https://github.com/opstrace/opstrace/issues/439#issuecomment-793731713

ci: run wipe-bk-tmp-dir after unit tests

---

lib/utils/src/index.ts
lib/utils/src/pubkey.ts
packages/cli/src/create.ts
packages/cli/src/crypto.ts
packages/controller/src/resources/apis/cortex.ts

https://github.com/opstrace/opstrace/issues/456
This kind of patch should be considered an exception.
It makes the newer controller version work with an older controller config, transparently. **Without migrating the config schema**. 
Such approach is difficult to maintain: when can the relevant code path be removed?
If we want to be able to do controller upgrades, we need to build a controller config schema migration system that keeps track of the controller config schema version, and explicitly performs a migration when upgrading the controller (which after all writes a new value to the k8s config map holding the controller config).

controller: deal with old config schema (param `data_api_authn_pubkey_pem`)

---

go/cmd/config/README.md
go/cmd/config/actions/types.go
go/cmd/config/actions/util.go
go/cmd/config/config_types.go
go/cmd/config/credential.go
go/cmd/config/exporter.go
go/cmd/config/hasura_handler.go
go/cmd/config/main.go
packages/app/docker-compose.yml
packages/app/metadata/actions.graphql
packages/app/metadata/actions.yaml
packages/controller-config/src/docker-images.json
packages/controller/src/dbSDK.ts
packages/controller/src/resources/app/api.ts
packages/controller/src/resources/app/app.ts

This should allow the UI to communicate with other things in the cluster, with Hasura/GraphQL acting as the common portal.
- Adds plumbing to Hasura for querying the config-api service, using a shared secret to authenticate Hasura to the service
- Implements calls for getting/setting the per-tenant alertmanager configuration in cortex
- Implements calls for validating credential/exporter configs

config: Implement Hasura Actions for alertmanager get/set and creds/exporters (#373)

---

go/cmd/config/README.md
go/cmd/config/actions/types.go
go/cmd/config/config_types.go
go/cmd/config/hasura_handler.go
packages/app/docker-compose.yml
packages/app/metadata/actions.graphql
packages/controller-config/src/docker-images.json

- Update config-api README: Adds examples for the other endpoints that the service now has.
- Switch `validateCredential` and `validateExporter` to be Queries: They aren't modifying anything server-side, so calling them Mutations doesn't really make sense. Mainly just a style thing.
- Update `validateCredential` and `validateExporter` parameters to align with the GraphQL queries for creating/updating credentials and exporters.
Note that `validateCredential` and `validateExporter` currently don't really work yet. There's some parser errors on the provided value/config input even if it's valid. This shouldn't take too long to fix, but the calls aren't being used yet, and there isn't a particular plan to start using them in the near future, so I'm going to leave them alone for now until …

config: Update config-api readme, update validateCredential/validateExporter

---

test/test-remote/prom-node-client-tools/index.ts

Fixes an issue in looker's `TimeseriesFragmentPushMessage.postWithRetryOrError()` where no waiting time was spent between POST HTTP request attempts when retrying was triggered by 5xx type responses (that really was an oversight, think of it as a missing sleep() statement). This is to address #480. This instability newly showed itself as of the 429 response rewriting implemented via #464.
429 responses were handled by design (with a small wait step inbetween attempts).

looker: ts fragment pusher: sleep between 5xx retries

---

containers/controller/Dockerfile
packages/app/README.md
packages/app/codegen.js
packages/controller/package.json
packages/controller/src/dbSDK.ts

Instead of copying the file from packages/app in the controller build, just update both copies at once.
This avoids potential issues around the controller graphql code falling out of date vs the app graphql code.
As a future improvement, the graphql schema itself could be moved into a separate package. However it depends on Hasura, so we'd probably need to bring that along as well, at which point it starts entering "can of worms" territory in terms of updating build/dev tooling.

controller: Generate controller graphql API alongside other copies

---

lib/kubernetes/src/reconciliation/reconcile.ts
packages/controller/src/tasks/reconciliation.ts
packages/uninstaller/src/informers.ts
packages/uninstaller/src/readiness.ts

1. To disable controller management of a given resource, remove or rename the `opstrace` annotation.
2. When finished with the customizations, put the `opstrace` annotation back to return to normal.
This should make it straightforward to manually edit/override resources without the controller stomping on the edits, and without needing to shut off the controller entirely.
Also refactors/cleans up the duplicate logic in the reconciliation code, since this change required an addition to that logic.
(Fixes #467)

controller: When an existing resource lacks the 'opstrace' annotation, leave it as-is

---

test/test-remote/logstream-gen/index.ts
test/test-remote/loki-node-client-tools/dummystream.ts
test/test-remote/prom-node-client-tools/dummyseries.ts

For metrics mode: for basic retrying support around query GET requests, and for emitting the corresponding looker metrics around transient problems.

looker: metrics mode: use custom GET func

---

lib/kubernetes/src/reconciliation/reconcile.ts
packages/installer/src/secrets.ts

The `system-tenant-api-auth-token` secret lacked an `opstrace` annotation, so the controller would then log a (recently-added) notice about the secret not being a known/managed resource. Passing it via a `ResourceCollection` automatically configures the annotation. We also mark the secret as immutable since it's not explicitly included among the controller's expected resources.
As a minor change, the notice message is updated to include the type of the resource being logged (`Secret` in this example).

installer: mark system-tenant-api-auth-token as managed

---

Makefile
containers/ci/opstrace-ci.Dockerfile
go/Dockerfile.config
go/Dockerfile.cortex
go/Dockerfile.ddapi
go/Dockerfile.loki
go/cmd/cortex/proxy_test.go
go/go.mod
go/go.sum

Reopening #374 to upgrade to most recent Golang version.
Close #376

chore: bump golang to 1.16.2

---

docs/guides/user/collecting-cloud-metrics.md

Link checks have failed because GitHub pre-pends `user-content-` to their anchor IDs.
```
https://next-website-kvmd8gidr-opstrace.vercel.app/docs/guides/user/collecting-cloud-metrics
id #configuration not found	https://github.com/prometheus/cloudwatch_exporter#configuration
id #credentials-and-permissions not found	https://github.com/prometheus-community/stackdriver_exporter#credentials-and-permissions
id #credentials-and-permissions not found	https://github.com/prometheus/cloudwatch_exporter#credentials-and-permissions
id #flags not found	https://github.com/prometheus-community/stackdriver_exporter#flags
```

docs: fix links to github

---

go/cmd/config/main.go
packages/controller/src/helpers.ts
packages/controller/src/resources/cortex/index.ts
packages/controller/src/resources/ingress/index.ts
packages/controller/src/resources/monitoring/index.ts
packages/controller/src/resources/monitoring/tenants/alertmanager.ts

Update the Alertmanager UI endpoint at `https://<tenant>.<cluster>.opstrace.io/alertmanager` to point to Cortex
Configures the Ingress to set the X-Scope-OrgID header expected by cortex.

controller: Point alertmanager tenant ingress to cortex

---

ci/check-deployed-docker-images.sh
go/cmd/config/README.md
go/cmd/config/config_types.go
packages/controller-config/src/docker-images.json
packages/controller/src/resources/exporters/index.ts

Adds a new exporter type for the [blackbox exporter](https://github.com/prometheus/blackbox_exporter/). In practice it's used to check the uptime of things like web pages. This exporter is a little different from most because it serves multiple endpoints to prometheus, and we need to configure prometheus to query those endpoints.
- `modules` (optional): The exporter is configured with `modules` with [a default configuration](https://github.com/prometheus/blackbox_exporter/blob/master/blackbox.yml) if none is provided by the customer. Each module is one of four `prober` types (`http`, `tcp`, `dns`, `icmp`) and has various arguments for how the client should work. For example we may define a `dns_mx` module with `prober: dns` that should check for `MX` email DNS records, and then have …

controller: Support for deploying blackbox exporter (fixes #548)

---

.gitignore
go/cmd/config/actions/types.go
go/cmd/config/actions/util.go
go/cmd/config/hasura_handler.go
go/pkg/graphql/client_generated.go
packages/app/metadata/actions.graphql
packages/app/metadata/actions.yaml
packages/app/src/client/views/tenant/alertmanagerConfig/editor/index.tsx
packages/app/src/state/graphql-api-types.ts
packages/controller/src/dbSDK.ts

Rules are under Rule Groups, and Rule Groups are under Namespaces. Each tenant can have one or more Namespaces.
The underlying cortex API has calls at each level, but to keep it simple for now, this just adds the following Hasura calls:
- `listRules(tenant)`: List all Rules for the tenant (across all namespaces/groups)
- `getRuleGroup(tenant, namespace, group_name)`: Get a single Rule Group
- `updateRuleGroup(tenant, namespace, group_yaml)`: Create/update a Rule Group - unlike with `updateAlertmanager` this does not support delete because the `group_yaml` payload contains the Rule Group name
- `deleteRuleGroup(tenant, namespace, group_name)`: Delete a Rule Group (Namespaces auto-delete when empty) - separate call from `update` per note above
ALSO, renames `AlertmanagerUpdateResponse` to …

config: Hasura Actions for accessing cortex rules (#517)

---

go/cmd/config/credential_api.go
go/cmd/config/exporter_api.go
go/pkg/config/common.go
go/pkg/config/common_test.go

Ensure that they are safe to use in the names of K8s Secrets/Deployments/etc

config: Validate credential/exporter names (#475)

---

lib/dns/src/opstrace.ts

Exit installer early if cluster name is already taken and you don't own it.

chore: exit early if cluster name is already taken

---

packages/installer/src/certificates.ts

#557 had a bug when checking if the certificate failed or not. 
[Typescript playground](https://www.typescriptlang.org/play?#code/FAFwngDgpgBAwgewHYBMYG9g2zAtlAZwIEMBzKALhgJACcBLJUmAHxgFdUoAzRqFANzAAvsFCRYcKLRAYsOJMXxUaDJvOwBjZCnoh6yAlUSoA2gF1WHLryT8RY7UhoxN0-b03EQhY+4swALwwphoYisowAEQARlEANK46egbOVKbo+ERklDAABjGFecLmwvFh6BG5UcQJSagphumZhCTkVHkAKgAWsG4y9J7esLRQAI7shLLdxAQw3MT0ADb8MCAISbgQKz4wxKgwAO7LSzAxI1B09PxUAGKLK2jrR4uy3Ai0MB8o0jCjBAh2LQ3NFuiAQBACABafogKEAaxiADYxrgoUiACwADgAnAAGAk4gCsUTWG3O2nwfygxBQYCo31+9DmjGijAAbsQlvQUKSaMMKMVSsBzEJgDtXO4gpKBkMfAQAHS2FAAClhQQAfHIcNSQECkDKQAqnLp9IYAPxKxiqk2a7U6nCjPW0A0mhVZNpQS2MTRLdg-AgqqL3ZarZ6HV7zD5fWg-T7-QHAqBRACUQh1wjTIizwEGMDVUsCResP1s-BT9q0hgQKwVSwQpCDuhQSAA5LJDh94amRDAoEsCLBMDqnADa-XG1F3pw0Ho6rCFVUUw4gA) where I tested this change.

chore: fix missing return statement

---

.dockerignore
.gitignore
Makefile
lib/kubernetes/package.json
test/test-remote/README.md
test/test-remote/containers/looker/Makefile
test/test-remote/containers/looker/looker.Dockerfile
test/test-remote/containers/looker/tsconfig.json
test/test-remote/nodejs-testrunner.Dockerfile
test/test-remote/package.json
test/test-remote/test_alerts.ts
test/test-remote/test_dd.ts
test/test-remote/test_prom_remote_write.ts
test/test-remote/test_systemmetrics.ts
test/test-remote/testutils/index.ts
test/test-remote/testutils/portforward.ts

Deploys the 'e2ealerting' tool for firing alerts and checking that they are received.
See also: https://github.com/grafana/cortex-tools/blob/main/docs/e2ealerting.md
The chain works like this:
- The test deploys an `e2ealerting` pod
- `e2ealerting` pod serves a metric: `e2ealerting_webhook_receiver_end_to_end_duration_seconds`
- the metric is scraped by the tenant prometheus
- the tenant prometheus forwards it to cortex against the tenant (`X-Scope-OrgId`)
- cortex ruler has been configured with an alert rule to always fire against the metric
- cortex alertmanager has been configured to report firing rules back to `e2ealerting` via a webhook endpoint
- `e2ealerting` receives the alert, and then increments `e2ealerting_webhook_receiver_evaluations_total`
So, what we need to do is:
- Deploy …

test-remote: Implement E2E tests for alerts (#442)

---

lib/aws/src/autoScalingGroup.ts

Close #564 
I checked [Terraform code](https://github.com/hashicorp/terraform-provider-aws/blob/068ebd8bb5a703e92342ba69406746c993444033/aws/resource_aws_autoscaling_group_waiting.go#L22) to see how they handle this scenario. They [compare state](https://github.com/hashicorp/terraform-provider-aws/blob/068ebd8bb5a703e92342ba69406746c993444033/aws/resource_aws_autoscaling_group.go#L1057-L1060) using their internal data structures instead of relying on cloud provider state. This way they only trigger an AutoScaling group update if there are any desired changes.
I ended up settling on exit if the AutoScaling group activities are empty but the instance count is at the desired capacity.

fix: handle auto scaling group upgrade without recent activity

---

go/cmd/config/credential_api.go
go/cmd/config/exporter_api.go
packages/controller-config/src/docker-images.json
packages/controller/src/resources/exporters/index.ts
test/test-remote/test_alerts.ts
test/test-remote/test_exporters.ts
test/test-remote/testutils/index.ts
test/test-remote/testutils/portforward.ts

Across default+system tenants x cloudwatch+stackdriver+blackbox types: Configures the exporter using the `/api/` endpoint, then waits for the exporter to appear as a scrape target in tenant prometheus, then waits for a sample metric to appear in Cortex.
Cloud exporters are run with invalid/stub credentials, where we just check that debug metrics are getting through.
Also fixes:
- Update credential/exporter API list responses to consistently return list format when there are zero or one entries. (`GET /api/v1/credentials` and `GET /api/v1/exporters`)
- Insert per-probe module/target labels into blackbox exporter metrics, so that probes can be distinguished from one another.

test-remote: Implement exporter tests for each exporter type.

---

lib/kubernetes/package.json
lib/kubernetes/src/equality/index.ts
yarn.lock

Close #585 
Uses fast-deep-equal to check if the Ingress resource spec or annotations changed.
Tested locally with `DRY_RUN_KUBERNETES_API_WRITES=true LOG_LEVEL=debug node packages/controller/build/cmd.js loadtest `--external` and it found the differences.

fix: ingress equality check

---

ci/test-upgrade/run.sh

See https://github.com/opstrace/opstrace/issues/591 for more details.

ci(test-upgrade): remove base cluster sanity check

---

packages/controller-config/src/schema.ts
packages/controller-config/src/schemav1a.ts
packages/controller-config/src/schemav1alpha.ts

Between the use of ControllerConfig V1 and V2 schemas there was a cluster launched that had the tenant_api_authenticator_pubkey_set_json field but before logRetention and metricRetention were renamed.

chore: handle older controller config schema

---

test/test-remote/test_alerts.ts
test/test-remote/test_dd.ts
test/test-remote/test_exporters.ts
test/test-remote/test_prom_remote_write.ts
test/test-remote/test_systemmetrics.ts
test/test-remote/testutils/index.ts
test/test-remote/testutils/logs.ts
test/test-remote/testutils/metrics.ts

The Azure exporter fails to start when provided with bogus credentials, so we just check its logs to validate that it was deployed and that it failed to query Azure as expected. In comparison, when other exporters are faced with invalid credentials, they tend to instead expose a metric with a nonzero error count.

test-remote: Add test for azure exporter (#556)

---

test/test-remote/test_exporters.ts

If we're very lucky, we get back more than one `_`. This was seen in a scheduled build, where the token ended up being `0lpb_`, which I think maps to originally being `_lpb_` where only the first `_` was replaced.

test-remote: Replace ALL underscores with non-underscores, not just the first

---

packages/controller/src/helpers.ts
packages/controller/src/resources/cortex/index.ts
packages/controller/src/resources/loki/index.ts

Implements Proposal 2 described in #580.
Given the following ConfigMap, deployed with `kubectl` :
```
apiVersion: v1
kind: ConfigMap
metadata:
name: opstrace-controller-config-overrides
namespace: default
data:
cortex: |
limits_config:
max_label_names_per_series: 45 
loki: |
limits_config:
max_label_names_per_series: 45  
```
The controller will read the Cortex and Loki config overrides, merge them with the default configs and update all the deployments.

controller: allow cortex and loki config overrides

---

ci/test-cli/cli-tests-with-cluster.sh
packages/cli/src/aks.ts
packages/cli/src/index.ts
packages/cli/src/util.ts
packages/controller-config/src/tasks/api.ts

```
± node packages/cli/build/index.js ta-pubkeys-list --help
usage: opstrace ta-pubkeys-list [-h] [--log-level LEVEL] PROVIDER CLUSTER_NAME
Tenant authentication: list public keys for a running Opstrace cluster, i.e. the set of trust
anchors for signed authentication tokens. The configured public keys are listed via their key ID on
stdout, with one key ID per line.
positional arguments:
PROVIDER           The cloud provider to look up the Opstrace cluster in (aws, gcp).
CLUSTER_NAME       The name of the cluster to look up the authenticator configuration for.
optional arguments:
-h, --help         show this help message and exit
--log-level LEVEL  Set log level for output on stderr. One of: debug, info, warning, error.
Default: info
```
```
± node packages/cli/build/index.js …
```

CLI: add subcommand ta-pubkeys-list

---

.github/dependabot.yml

Let's avoid falling behind for the GH Actions that we use.

chore: add a dependabot config for github actions only

---

packages/controller-config/src/docker-images.json
packages/controller/src/resources/cortex/index.ts

https://github.com/cortexproject/cortex/releases/tag/v1.9.0-rc.0

cortex: bump to current HEAD of master

---

docs/references/cli.md

Found a text block with nothing in it...

docs(cli): fix missing example

---

packages/controller-config/src/docker-images.json
packages/controller/src/resources/memcache/index.ts

This also changes the resource requests a little bit, no magic to be expected from that change.
It's important to recognize the difference between resource requests and resource limits in k8s: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#requests-and-limits

bump: memcached 1.6.6 -> 1.6.9

---

packages/app/src/client/views/alerting/configuration.tsx
packages/app/src/state/tenant/sagas/index.ts

The are two independent fixes in this PR:
1. Recent changes removing alertmanager template editing also ment those templates were not being included when saving configuration changes, what was resulting in a server side validation error. This fix simply includes the default set of templates when saving which is the same as the prior behaviour if the user didn't edit the templates.
2. As the user was updating the alertmanager configuration validation checks were performed to dynamically enable/disable the "save" button but those changes were not additionally being kept for use when the "save" button was clicked. This change now keeps the user's changes in `dataRef`. FYI: the underlying issue here is that we can't directly query the monaco editor for it's current value when the user hits …

ui: bugfix for "can't save alertmanager configuration changes made in the UI"

---

.gitignore
packages/app/src/client/app.tsx
packages/app/src/client/views/cluster-overview/index.tsx
packages/app/src/client/views/overview/index.tsx
packages/controller/src/resources/monitoring/tenants/grafana.ts

**Cluster health:**
The "opstrace overview" dashboard is temporarily used for the following tenant overview. Dedicated tenant overview dashboard coming soon.
**Tenant overview:**

Show tenant overview page and cluster health

---

packages/app/src/client/components/Grafana/Iframe.tsx
packages/app/src/client/themes/Provider.tsx
packages/app/src/client/views/cluster-overview/index.tsx
packages/app/src/client/views/overview/index.tsx
packages/app/src/state/tenant/hooks/useTenantList.ts
packages/app/src/state/user/actions.ts
packages/app/src/state/user/sagas/index.ts
packages/controller/src/resources/ingress/index.ts

Setting darkmode is now applied cluster-wide for a user, meaning it's applied to the Opstrace UI and all Grafana instances the user has access to.
https://www.loom.com/share/cf8de1e6c6064cdea8e8143d0aed6302

Sync Opstrace user's preferences (darkmode) to all Grafana instances across user's tenants

---

packages/app/src/client/viewsBasic/integrationDefs/k8sMetrics/index.tsx
packages/app/src/client/viewsBasic/tenantIntegrations/Add.tsx

And stop harding coding to it when creating an I9n
This fixes a 404 being seen when looking at "show" page for k8s-metrics integrations

ui: specify correct "kind" value for K8sMetrics I9n definition

---

lib/kubernetes/src/equality/Pod.ts
lib/kubernetes/src/equality/PrometheusRule.ts
lib/kubernetes/src/equality/Service.ts
lib/kubernetes/src/equality/ServiceMonitor.ts
lib/kubernetes/src/equality/utils.ts

As discussed [here](https://opstrace-community.slack.com/archives/C01KZS8JRNC/p1620654448097300?thread_ts=1620653118.096800&cid=C01KZS8JRNC), this change reduces a bit of duplication be re-using the array checks in the code that detects changes in k8s resources.

feat: re-use array equality check logic

---

packages/app/src/client/components/Grafana/Iframe.tsx

Fixes a bug that recently found its way into main, that prevents the dashboards from showing on the Tenant Overview and Cluster Health pages.
Integration test coming in a follow up PR.

Fix bug that prevents the dashboards from showing on the Tenant Overview and Cluster Health pages

---

packages/config/src/gke.ts

GKE 1.18 no longer available in regular channel (as of midnight last night)

---

ci/deploy-testremote-teardown.sh
ci/test-upgrade/teardown.sh
ci/test-upgrade/upgrade-cluster.sh

The destroy command searches for the cluster in all the available AWS regions and sometimes it can timeout and fail to cleanup resources. We don't return an error code to signal this timeout error so the workaround is to retry the teardown in the known region when the initial command fails. The CI run will fail to signal the initial teardown error to ensure we look at the failure.
The upgrade test and command share the same issue so I just hardcoded the region to prevent any more resource leakage.

ci: retry teardown in AWS region if initial command failed

---

packages/app/babel.config.js
packages/app/config/webpack.config.js
packages/app/config/webpack.server.config.js
packages/app/package.json
yarn.lock

The UI Server app started using a package containing unsupported ?? syntax. This stopped the server from starting successfully due to a syntax error.
@opstrace/kubernetes was [recently included](https://github.com/opstrace/opstrace/commit/8ac0b7deae32316c3461cdce5a3477f588b1b9ab) in the package.json as part of PR https://github.com/opstrace/opstrace/pull/760 which resulted in this error when running `yarn server:start`
```
ERROR in <snip>/opstrace/lib/kubernetes/build/readiness/certificates.js 27:152
Module parse failed: Unexpected token (27:152)
File was processed with these loaders:
* ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
| 
|   const certificate = c.spec;
>   const conditions = ((_certificate$status = …
```

ui: fixed - app server started using package containing unsupported ?? syntax

---

packages/app/migrations/1621731892198_alter_table_public_integration_add_column_tenant_name/down.sql
packages/app/migrations/1621731892198_alter_table_public_integration_add_column_tenant_name/up.sql
packages/app/migrations/1621731969932_alter_table_public_integration_drop_column_tenant_name/down.sql
packages/app/migrations/1621731969932_alter_table_public_integration_drop_column_tenant_name/up.sql

Recently migrations that added then removed the `tenant_name` field on the `integrations` table were accidently commited. These have caused a problem as the migration adding the `tenant_name` field has it set as `NOT NULL` but doesn't do anything towards migrating existing records in the `integrations` table meaning the migration fails when run against a populated table.
This leaves the `graphql` pod in a crash loop, the following error is logged:
```
time="2021-05-25T04:44:53Z" level=fatal msg="apply failed: [postgres-error] query execution failed ($.args[12].args)\r\nFile: '1621731892198_alter_table_public_integration_add_column_tenant_name/up.sql'\r\n{\n    \"check_metadata_consistency\": false,\n    \"sql\": \"ALTER TABLE \\\"public\\\".\\\"integration\\\" ADD COLUMN …
```

ui: removing accidentially commited migrations that were breaking upgrading a cluster with defined integrations

---

.buildkite/cd-pipeline.yml
Makefile
ci/cd/cluster-config.yaml
ci/cd/dns-service-credentials.sh
ci/cd/fetch-cli-artifacts.sh
ci/cd/fetch-secrets.sh
ci/cd/run.sh
ci/cd/upgrade-cluster.sh
packages/upgrader/src/index.ts
packages/upgrader/src/upgrade.ts

Add a Buildkite pipeline to upgrade a long running cluster to the latest version. The cluster is ingesting 2.5M metrics. I'll set up the pipeline to run once a day.
Also, fixes a bug I noticed when upgrading the cluster to the same version. The CLI should exit early if a controller rollout is not required.

ci: add a buildkite pipeline to upgrade a long running cluster

---

ci/test-upgrade/fetch-cli-artifacts.sh

Makes it easier to test upgrades for CLIs built from PRs.
You can create a Buildkite build with the following env vars to choose which artifacts will be used in the test.
```
OPSTRACE_CLI_VERSION_FROM=cli/main/6cb91909-ci/opstrace-cli-linux-amd64-6cb91909-ci.tar.bz2
OPSTRACE_CLI_VERSION_TO=cli/main/latest/opstrace-cli-linux-amd64-latest.tar.bz2
```
Close #738

ci(upgrades): fetch artifacts from full s3 resource uri

---

packages/app/src/client/views/ring-health/TokenDialog.tsx

Improve the ways tokens are displayed in the health metric's token dialog.
Dialog itself is responsiveness, and content is organised in 1-3 columns, depending on screen size.

feat(TokenDialog): improve displaying of tokens

---

go/pkg/graphql/client_generated.go
packages/app/migrations/1622501245248_alter_table_public_integration_add_unique_key_tenant_id/down.sql
packages/app/migrations/1622501245248_alter_table_public_integration_add_unique_key_tenant_id/up.sql
packages/app/src/state/graphql-api-types.ts
packages/controller/src/dbSDK.ts

updated unique constraint on the integration table to be `key+tenant_id`

ui: fix - integration.key should be unique per tenant, not per cluster

---

Makefile
containers/ci/opstrace-ci.Dockerfile

Increase timeout to handle failures when the build agent is busy.
Close #709 
Close #166

bump: golangci-lint to v1.40.1 and increase timeout

---

packages/app/src/client/services/Picker/types.ts
packages/app/src/client/views/tenants/TenantPicker.tsx
packages/app/src/state/global/actions.ts
packages/app/src/state/integration/reducer.ts
packages/app/src/state/integration/sagas/integrationListSubscription.ts

This creates a global action which gets dispatched when the currently selected Tenant is changed by the user - any reducer can respond to it, in this case the Integration reducer resets it's state so as to not containt Integrations for the wrong Tenant

ui: global redux actions for tenant change

---

packages/app/src/client/views/ring-health/RingTable.tsx
packages/app/src/client/views/ring-health/cortex/index.tsx
packages/app/src/client/views/ring-health/loki/index.tsx

Removes this warnings:
The tabs were already expecting values, before the routing was done. To fix this, I moved the tabs within the routes.

fix(app): error log in ring health

---

test/test-remote/logstream-gen/index.ts
test/test-remote/loki-node-client-tools/dummystream.ts
test/test-remote/loki-node-client-tools/index.ts
test/test-remote/prom-node-client-tools/dummyseries.ts
test/test-remote/prom-node-client-tools/index.ts

```
This is an intermediate state, introducing
the concept of serializing N series fragments
into a single push request. That will greatly
enhance the flexibility and application scenarios
for looker.
Note that this is an inner architecture change,
more thinking and work required until this is
exposed to users.
```

looker: work towards N streams per push request

---

ci/test-upgrade/create-cluster.sh

The initial cluster version, 6cb91909-ci, does not recognize the `--instance-config` flag name.

ci(upgrades): fix invalid flag

---

README.md
docs/guides/administrator/upgrading.md
docs/guides/contributor/workflows.md
docs/quickstart.md

Now that we have proper releases — 🎉 — we should point our documentation to those binaries (instead of the latest from CI).

chore: update links to point to latest released CLI binaries

---

packages/cli/src/util.ts
packages/installer/src/index.ts
packages/upgrader/src/index.ts

@jgehrcke already updated much of the user-facing CLI output in #829.  While I understand and agree that the log message output is not written for humans, I would like to update the very last lines that come out of the CLI to make them compliant with our new guidelines.  
UPDATE:  aside from making these consistent for our users, it's important to make these consistent for screenshots, gifs, etc.

chore: update additional user-facing text removing "cluster"

---

test/test-remote/logstream-gen/index.ts
test/test-remote/loki-node-client-tools/index.ts
test/test-remote/prom-node-client-tools/index.ts

This further evolves the architecture towards being able to easily put N time series fragments into a single push request.

looker: n fragments per pushrequest dev

---

packages/cli/src/upgrade.ts
packages/cli/src/util.ts

@MoSattler reported on Slack that with the wording of the error message prior to this patch it took him a minute to realize that what he wants to achieve can be done by adding `--region <region>`:
> nevermind, setting the region actually makes it work again (as the output says :face_palm:)
This patch tries to make this clearer, by explicitly mentioning the scenario of the previously only partially destroyed Opstrace instance:
> ... For cleaning up resource residuals of a previously only partially destroyed Opstrace instance, you can force-run the 'destroy' operation ...

cli: destroy: try to clarify --region force-run

---

test/test-remote/nodejs-testrunner.Dockerfile
test/test-remote/package.json
yarn.lock

also updated to latest version of playwright.
Turns out there is a known and unresolved issue where yarn can fail to download playwright browser binaries, npm doesn't have this issue. https://github.com/yarnpkg/yarn/issues/7887. I've been encountering this on my local development environment so ended up looking into it a bit.
The suggested workaround is to manually install the binaries so giving that a try
https://github.com/microsoft/playwright/issues/581#issuecomment-585506945
https://github.com/microsoft/playwright/issues/598#issuecomment-590151978

[WIP] ui: manually installing playwright browser binaries with node as yarn is flakey

---

packages/controller/src/resources/monitoring/system/dashboards/opstrace-overview.json

- (metrics) Update series panel to include both 'in-memory' and 'active' measures of series
- (metrics+logs) Add panel for in-flight ingester requests, showing if ingesters are falling behind
- (metrics+logs) Add panel for ingester heap object counts, tracking cache/pending request size
- (metrics) Add WIP panel for compactor error rate, but doesn't seem to be a great indicator yet...

cortex: Update Opstrace Overview dashboard to track ingester/series status

---

docs/guides/administrator/gcp-setup.md

Fix error
```
[2021-06-09T04:03:32Z] docs/guides/administrator/gcp-setup.md:19
MD022/blanks-around-headings/blanks-around-headers Headings should
be surrounded by blank lines [Expected: 1; Actual: 0; Above]
[Context: "## Step 2: set up the  `gcloud` CLI"]
```

docs: fix markdown lint error

---

test/test-remote/logstream-gen/index.ts

Manual test, log output:
```
2021-06-09T13:31:25.259Z info: End of write phase. Log entries / metric samples sent: 5000000, Payload bytes sent: 40.00 million
2021-06-09T13:31:25.259Z info: Payload write net throughput (mean): 0.63 million bytes per second (assumes utf8 for logs and 12+8 Bytes per sample for metrics)
2021-06-09T13:31:25.261Z info: cycle 3: entering read phase
2021-06-09T13:31:25.261Z info: entering read / validation phase
2021-06-09T13:31:25.262Z info: randomly picking 2/100 streams for validation
...
"write": {
"nEntriesSent": 5000000,
"nPayloadBytesSent": 40000000,
"entriesSentPerSec": 78355.28642431553,
"megaPayloadBytesSentPerSec": 0.6268422913945242,
"durationSeconds": 63.811903806
},
"read": {
"nEntriesRead": 100000,
"nPayloadBytesRead": 800000,
"entriesReadPerSec": …
```

looker: add --read-n-streams-only feature

---

packages/app/src/client/utils/regex.ts

The entire site does not render at all due to the use of the "look behind", have re-written the regex to remove that.

ui: fix - webkit failing to render due to unsupported lookbehind syntax used in regex

---

packages/app/src/client/integrations/common/UninstallIntegrationBtn.tsx
packages/app/src/client/integrations/exporterAzure/Form.tsx
packages/app/src/client/integrations/exporterAzure/Show/index.tsx
packages/app/src/client/integrations/exporterCloudMonitoring/Form.tsx
packages/app/src/client/integrations/exporterCloudMonitoring/Show/index.tsx
packages/app/src/client/integrations/exporterCloudWatch/Form.tsx
packages/app/src/client/integrations/exporterCloudWatch/Show/index.tsx
packages/app/src/client/views/integrations/all/Add.tsx

Also providing a direct link to it on the detail page for the integration. Makes a default folder for users to create dashboards in.

ui: automatically create/destroy grafana dashboard folder for exporter integrations

---

packages/controller/src/resources/cortex/index.ts

The ingester readiness check is based on the ring status of all ingesters.
As a result you can end up with e.g. ingester-1 refusing to deploy because ingester-5 is unhappy.
The StatefulSet will then refuse to deploy ingester-5 because it wants ingester-1 to be ready first.
This breaks the dependency cycle by allowing ingesters to deploy (and/or scale out) in parallel. Note that it does not affect the rollout of config changes, which will remain sequential.

controller: Configure ingesters to not block on readiness (of other ingesters)

---

package.json
yarn.lock

Bump vercel/pkg, also unlocking
an important bump towards newer
nodejs 14.x releases.
```
> Fetching base Node.js binaries to PKG_CACHE_PATH
fetched-v14.17.0-linux-x64
Done in 51.09s.
+ set +o xtrace
Successfully built CLI for linux: ./build/bin/opstrace
```

cli: pkg 5.2.1 / nodejs 14.17.0

---

packages/controller/src/resources/cortex/index.ts

When scale testing, we explicitly want more ingesters when we add more nodes.  This is a bit of a specific fix for that use case, rather than a well-thought-out strategic change.

chore: allow for more ingesters when there are more nodes

---

test/test-remote/test_ui.ts

Adding E2E tests for ring health. 
- Navigates to the health metrics, opens each tab (`Ingester`, `Ruler`, etc), and checks if the table loads.
- It assumes that when at least one row with valid content for the "Last heartbeat" cell is rendered, that the table loaded correctly, and the test passes.
- Excluding Alert Manager for the moment, as there is a problem that prevents it from working right now, see [here](https://opstrace-community.slack.com/archives/C01KZS8JRNC/p1623664061091000).

ui(test-remote): add test case for ring health

---

test/test-remote/test_ui.ts

Since a [previous bug](https://opstrace-community.slack.com/archives/C01KZS8JRNC/p1623665131091100?thread_ts=1623664061.091000&cid=C01KZS8JRNC) was fixed [here](https://opstrace-community.slack.com/archives/C01KZS8JRNC/p1623704267093500?thread_ts=1623664061.091000&cid=C01KZS8JRNC), we can reactivate the alert manager test.

test-remote(ring-health): add alertmanager to tests

---

.gitignore
Makefile
ci/cd/run.sh
ci/deploy-testremote-teardown.sh
ci/test-upgrade/run.sh
test/browser/.dockerignore
test/browser/Dockerfile
test/browser/fixtures/authenticated.ts
test/browser/package.json
test/browser/playwright.config.ts
test/browser/playwright.dev.config.ts
test/browser/tests/authentication.spec.ts
test/browser/tsconfig.json
test/browser/utils/authentication.ts
test/browser/utils/index.ts
test/test-remote/package.json
test/test-remote/test_ui.ts
test/test-remote/testutils/index.ts
yarn.lock

Currently we don't do any browser testing with playwright, but rather only use playwright to get auth credentials to use in some direct API calls. Our current setup doesn't allow for multi-browser testing either which we need to have.
This PR moves to using the Playwright Test runner which is designed for running multi-browser tests with. This means moving to a different test file structure and separating out actual browser tests into a new section. Initially there are two simple tests to show that the user can login and navigate the site and see the correct content that are run against Chromium, Firefox, and Webkit
Additionally this PR runs the tests in a new docker image based on the official Playwright image that has all the browsers and their dependencies correctly installed. There …

[wip] ui: Multi-Browser test suite

---

packages/controller-config/src/docker-images.json
packages/controller/src/resources/monitoring/tenants/grafanaDatasources.ts
test/test-remote/test_ui.ts

Let's look at
```
location / {
...
set $backend http://querier.loki.svc.cluster.local:1080/$request_uri;
proxy_pass $backend;
}
```
Let's distinguish four cases.
* This adds a double slash from Loki's point of view, because `$request_uri` always starts with a slash (probably a cause for #908, see https://github.com/opstrace/opstrace/issues/908#issuecomment-863960135):
```
set $backend http://querier.loki.svc.cluster.local:1080/$request_uri;
```
* This always presents just `/` to Loki, forgets about the incoming URL path:
```
set $backend http://querier.loki.svc.cluster.local:1080/;
```
* These two are correct and equivalent for the special case of `location /`:
```
set $backend http://querier.loki.svc.cluster.local:1080;
```
```
set $backend …
```

Try to fix nginx datasource splitter reverse proxy config

---

packages/app/src/client/views/ring-health/RingHealth.test.tsx
packages/app/src/client/views/ring-health/RingTable.tsx
packages/app/src/client/views/ring-health/cortex/CortexRingHealth.test.tsx
packages/app/src/client/views/ring-health/loki/LokiRingHealth.test.tsx
packages/app/src/client/views/ring-health/testUtils.ts

Superset of #915  
Moving some of tests of implementations of `RingHealth` to the reusable component, to facilitate better testing of different aspects, e.g. fetching and error handling.

ui(ring-health): improve tests

---

packages/app/config/jest/setupTests.js

CI has a flake where unit tests sometimes timeout when the timeout is 15 seconds.
Increasing timeout _significantly_ will hopefully tell us if the timeout just needs to be increased, or if the test setup has a flaw (if this still fails).
Signed-off-by: Mat Appelman <mat@opstrace.com>

Bump unit test timeout to 5 mins for experimentation

---

packages/controller-config/src/docker-images.json

Until we root cause https://github.com/opstrace/opstrace/issues/905 and fix the failing upgrades test let's revert the Loki bump.
I'll run the upgrades test pipeline for this PR when the cli build artifacts are published.

controller: revert loki bump

---

Makefile
ci/deploy-testremote-teardown.sh
lib/dns/src/opstrace.ts

We re-deployed the DNS service with authentication architecture changes. This here is the corresponding change in our CI, so that CI can successfully authenticate itself towards the DNS service.

ci: use magic token for authn towards DNS service

---

packages/controller-config/src/docker-images.json
packages/controller/src/resources/loki/index.ts

Let's see if we can fix #905.
* Bump loki to 2.2.1 since we now know it's not related to the version bump.
* Fix the ingester terminationGracePeriod
* Enable wal 
* Remove livenessProbe because it prevents the use of the /ingester/flush_shutdown endpoint

loki: enable wal

---

packages/app/package.json
packages/app/src/client/views/ring-health/RingHealth.test.tsx
packages/app/src/client/views/ring-health/RingTable.tsx
packages/app/src/server/routes/api/cortex/cortex.test.ts
packages/app/src/server/routes/api/cortex/index.ts
yarn.lock

This PR addresses the problem mentioned [here](https://opstrace-community.slack.com/archives/C01KZS8JRNC/p1623664061091000), where Cortex is returning configuration "errors" via an HTML response. This was partially [addressed in the client](https://github.com/opstrace/opstrace/pull/876).
This client aims to abstract this behaviour away from the client and moves it to the proxy, while also extracting the error message to inform the user about the cause.

ui(ring-health): improve HTML error handling

---

packages/controller-config/src/resources/controller.ts
packages/controller/src/resources/apis/cortex.ts
packages/controller/src/resources/apis/dd.ts
packages/controller/src/resources/apis/loki.ts
packages/controller/src/resources/app/api.ts
packages/controller/src/resources/app/app.ts
packages/controller/src/resources/storage/gcp.ts

As far as I can tell, there is no real reason to use an image pull policy of `Always` for some of our pods; this just adds extra requests to the registry which can trigger rate limits.  Instead, this PR switches the policy to `IfNotPresent`, similar to most of the other pods.

controller: switch pull policy from Always to IfNotPresent to reduce requests

---

packages/app/src/state/cortex-config/sagas/cortexConfigSubscription.ts
packages/app/src/state/integration/sagas/integrationListSubscription.ts
packages/app/src/state/store.ts
packages/app/src/state/tenant/sagas/tenantListSubscription.ts
packages/app/src/state/user/sagas/userListSubscription.ts

Quick fix for https://github.com/opstrace/opstrace/issues/967. 
Of course we may want to set proper return types instead.

app: ts-ignore: TS7075 generator lacks return type

---

ci/cd/run.sh
ci/test-upgrade/preamble.sh

Target was renamed in #952 but calls weren't updated.

ci: fix target rename

---

go/pkg/authenticator/jwt.go

Default log level is info and in busy instances, handling hundreds of requests per second, this message spams the logs.
Found this tracking down why systemlog fluentd CPU usage was higher than expected;
cortex-api pod logs:

go: log as debug message

---

Makefile
test/test-remote/nodejs-testrunner.Dockerfile

* Some of the test targets don't require kubeconfig to be set up.
* Add gcloud cli to test-remote container. The cli is required to refresh expired kubeconfig credentials.
Close #977

ci: set up gcloud in test-remote container

---

Makefile
ci/cd/run.sh
ci/deploy-testremote-teardown.sh
ci/test-upgrade/run.sh
test/browser/Dockerfile
test/browser/fixtures/authenticated.ts
test/browser/playwright.config.ts
test/browser/tests/debugging.spec.ts

This is a re-do of https://github.com/opstrace/opstrace/pull/956 to get around an automated merge with main issue and so as to not pollute main with all my debugging CI commits.
The problem this resolves is that FF was not running on CI at all, was getting no debug output from fail tests etc.. It would do the initial auth step for the worker. What was happening was that the user ID being set in the `docker run` command was causing FF to not run. I don't have any links to this but from the huge amount of reading through various github issues that's what was likely the cause and then when I let it run as root everything worked.

ui: changes to enable FF in browser tests

---

ci/test-upgrade/preamble.sh

Upgrades were failing to build the test-remote docker image but kept running anyway because the preamble step was missing the bash incantantion.
Upgrades error:
```
[2021-07-04T20:55:41Z] error Command failed with exit code 2.
[2021-07-04T20:55:41Z] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
https://buildkite.com/opstrace/upgrade-tests/builds/928#f3ac88f3-790c-46ef-ad50-a8d648d49297/1064-2569

ci(test-upgrade): exit early if a command fails

---

ci/create-cluster-artifacts.sh
ci/dns_cache.sh

To help track down recent DNS not found errors as reported in #834.

ci: collect unbound logs

---

Makefile
test/browser/Dockerfile
test/browser/tests/authentication.spec.ts
test/browser/tests/debugging.spec.ts

refer to the related issue: https://github.com/opstrace/opstrace/issues/991
I will be hitting rebuild a few times on this PR to exercise the change on CI to see what effect the `--retries 1` setting has.

ui: have CI retry failed browser tests

---

packages/app/src/state/tenant/reducer.ts
test/browser/tests/tenant.spec.ts

doing this doesn't resolve the Apollo Client warning, but now it works from the user's perspective.

ui: updated Tenant reducer to handle delete action

---

test/test-remote/looker/src/args.ts
test/test-remote/looker/src/index.ts
test/test-remote/looker/src/metrics/dummyseries.ts

Randomness is provided via `invocation_id`, and then uniqueness across cycles and concurrent_streams is added on top via the indexes. End result:
- Metrics:
- metricName: `<invocation_id>-<cycle#>`
- uniqueName: `<invocation_id>-<cycle#>-<stream#>`
- Logs:
- uniqueName: `<invocation_id>-<cycle#>-<stream#>`
With all the randomness moved into `invocation_id` (and with it exposed in the args), it can be overridden manually, allowing e.g. series counts to remain stable across looker runs - or the caller can guarantee unique values by using a custom randomness.
---
ALSO:
Add args for configuring range of metric series start times: Allow using ranges other than default 20-30 minutes.

looker: Shift label randomness into invocation_id, allow configuration 

---

ci/test-upgrade/create-cluster.sh
ci/test-upgrade/initial-cluster-config.yaml

Copy the cluster-config.yaml to test-upgrade folder and remove the new field. Use that as the instance config for the initial cluster because the cli cannot parse the file.
Close #1013

ci(test-upgrade): correct version of cluster config schema

---

packages/cli/src/status.ts

Tried bumping the [request timeout](https://github.com/opstrace/opstrace/blob/29bb931b2ff765b445ce0632d1d76f0971e6879e/packages/installer/src/index.ts#L479) in the hopes it would help fix the issue but it didn't seem to make a difference.
Might as well bump the timeout as [suggested here](https://github.com/opstrace/opstrace/issues/981#issuecomment-877114437).

cli(status): bump check cluster status wait timeout

---

ci/test-cli/cli-tests-with-cluster.sh
packages/installer/src/index.ts
packages/upgrader/src/index.ts

From a recent upgrades pipeline [build](https://buildkite.com/opstrace/upgrade-tests/builds/953#8d5e2359-b655-4505-97a0-87c0f4f45610/2115-3404)
```
[2021-07-09T12:45:18Z] 2021-07-09T12:45:18.838Z debug: https://cortex.default.upgrade-bk-953-29b-g/api/v1/labels: HTTP request failed with: getaddrinfo ENOTFOUND cortex.default.upgrade-bk-953-29b-g
```
It's missing the `opstrace.io` domain.

cli(upgrades): fix invalid instance dns name

---

packages/app/src/client/app.tsx

Removed condition in the root App component that would only allow the rendering to continue if there was a selected tenant.

ui: bug fix - app can load without a tenant being selected via cluster routes

---

packages/app/src/client/services/Picker/PickerService.tsx
packages/app/src/client/services/Picker/types.ts
packages/app/src/client/utils/regex.ts
packages/app/src/client/views/tenants/AddTenantDialog.tsx
packages/app/src/state/tenant/utils.ts
test/browser/tests/tenant.spec.ts
test/browser/utils/tenant.ts

In the validation callback for the AddTenantDialog we are checking the typed name against the existing list of Tenants

[wip] ui: ensure new tenant name is unique

---

Makefile
test/browser/README.md
test/browser/fixtures/authenticated.ts
test/browser/fixtures/config.ts
test/browser/fixtures/index.ts
test/browser/fixtures/tenant.ts
test/browser/package.json
test/browser/tests/authentication.spec.ts
test/browser/tests/debugging.spec.ts
test/browser/tests/everywhere.spec.ts
test/browser/tests/tenant.spec.ts
test/browser/utils/authentication.ts
test/browser/utils/index.ts

We're having some frustrating intermittent timeout issues on CI with the browser tests at the moment. Sometimes it's looking to be occuring during the auth setup as part of the worker. When this happens we get no debug artefacts from playwright.
This change allows toggling the auth to occur either once per worker as it current occurs, or to happen before each test - which the CI tests are now set to do. Hopefully this will help debug the problems we're having.

[wip] ui: do auth as part of each browser test rather than per worker

---

test/test-remote/test_ui.ts

quick and dirty change to see what effect it has.

ui: double page timout in test_ui for the initial performLoginFlow used to capture auth cookies

---

ci/deploy-testremote-teardown.sh
packages/app/migrations/1626132643036_alter_table_public_tenant_add_check_constraint_tenant_name_validation/down.sql
packages/app/migrations/1626132643036_alter_table_public_tenant_add_check_constraint_tenant_name_validation/up.sql

Done in support of https://github.com/opstrace/opstrace/issues/710
Worth noting that presently we are being extermely restrictive on what can be in a Tenant named - only lowercase alphanumeric chars. This migration will fail when applied to existing data that violates the constraint.

ui: added UI tenant name regex validation as postgresql contraint check

---

Makefile
test/test-remote/containers/fluentbit/fbit.config.template
test/test-remote/test_loki_log_ingest_api.ts
test/test-remote/testutils/fbit.ts
test/test-remote/testutils/index.ts

This test covers a legacy tenant API authentication mechanism which landed [yesterday](https://github.com/opstrace/opstrace/pull/1035), where the tenant API authentication token is communicated via the `Basic` Authorization header scheme.
Notes about the non-obvious considerations:
* A containerized Fluent Bit is used as the log source.
* The Fluent Bit image used in this test is built by Grafana CI. Dockerfile in the Loki repo at `/clients/cmd/fluent-bit/Dockerfile`, e.g. https://github.com/grafana/loki/blob/a9d85de4aa5290cf2f8b2dca5d08645bbd0dc66c/clients/cmd/fluent-bit/Dockerfile -- documentation is here: https://grafana.com/docs/loki/latest/clients/fluentbit/ (and it's out of date)
* The Grafana Fluent Bit image is not based on most recent Fluent Bit releases, actually quite behind as …

test-remote: use containerized Fluentbit (with Grafana's Loki plugin), use Basic auth scheme

---

packages/app/migrations/1626017036575_simplify-existing-tenant-names/down.sql
packages/app/migrations/1626017036575_simplify-existing-tenant-names/up.sql

If a cluster has tenant names that contain chars that violate the newly added constraint on the tenant.name field upgrading the cluster will fail (well, atleast the hasura migrations will) with the following error:
```
FATA[0000] apply failed: [postgres-error] query execution failed ($.args[0].args)
File: '1626132643036_alter_table_public_tenant_add_check_constraint_tenant_name_validation/up.sql'
{
"check_metadata_consistency": false,
"sql": "alter table \"public\".\"tenant\" add constraint \"tenant_name_validation\" check (name ~ '^[a-z0-9]{2,63}$'::text);\n"
}
[23514] FatalError: check constraint "tenant_name_validation" is violated by some row 
```
This PR inserts a migration that runs immediately before the constraint is added. It ensures all tenant names will pass the new constraint …

[wip] ui: update constraint violating tenant names before constraint is added

---

lib/kubernetes/src/index.ts
packages/cli/src/create.ts
packages/controller-config/src/index.ts
packages/controller-config/src/tasks/api.ts
packages/controller-config/src/utils.ts
packages/installer/src/index.ts

See #20 and #237, also commit messages and code comments.

installer: do not update controller config if it exists

---

packages/controller/src/resources/loki/index.ts

Move to another port to avoid any possibility of joining pods belonging to cortex memberlist ring.
Copying the comment from https://github.com/opstrace/private/issues/169#issuecomment-879736441
> Just conjecture at this point but the constant crash looping of the pods could lead to the kubelet recycling IP addresses. Meaning, at some point, a pod belonging to one memberlist ring (cortex) could get an IP that was recently assigned to a pod in the other memberlist ring (loki). This would mean the new pod would connect to cortex memberlist ring but get connections from members of the loki ring. This would create the "bridge" between the two rings. I thought about this because left_ingesters_timeout is set to 5m0s which seems like enough time for an ingester to be up and advertise itself on …

loki: move memberlist bind port to 7947

---

.buildkite/test-upgrade-pipeline.yml
ci/test-upgrade/create-cluster-artifacts.sh
ci/test-upgrade/run.sh
ci/test-upgrade/set-up-test-tenant.sh
ci/test-upgrade/wait-for-loki-ring.sh

~In upgrades pipeline, run test-core.sh in a container using CI docker image. This is required to fix the missing gcloud and aws binaries to refresh credentials.~
~Did some changes to make docker create the test artifact folders but need to check it still runs the PR pipeline.~
See https://github.com/opstrace/opstrace/pull/1065#issuecomment-881414748 bello

ci(upgrades): dissociate test-core

---

lib/utils/src/buildinfo.ts

Local dev for the `packages/app` stopped working with [this commit](https://github.com/opstrace/opstrace/commit/b13281f18da1). So as to not add further complexity to running the app locally I've updated `readBuildInfo` to use a default set of values instead of erroring when `process.env.NODE_ENV === "development"`.

utils: when running local dev env use a default BUILD_INFO if there isn't a real one to use

---

ci/test-upgrade/run.sh
ci/test-upgrade/set-up-test-tenant.sh
ci/test-upgrade/wait-for-loki-ring.sh
packages/upgrader/src/index.ts
packages/upgrader/src/workaround.ts

Close #1066
The distributors need a kick start to find the ingesters, otherwise, we might get distributors thinking the ring is still empty. This is a consequence of the controller not deploying resources in a specific order. The ring state [eventually gets consistent](https://github.com/opstrace/opstrace/pull/1053#issuecomment-880288386) but it might take a long time. To make things faster go ahead and kick start the distributors after the initial rollout completes.

cli(upgrades): force distributor roll out after loki upgrade finishes 

---

packages/app/src/client/integrations/k8sMetrics/Show/templates/config.ts

We currently scrape kubelet `/metrics`. This adds `/metrics/cadvisor`, `/metrics/probes`, and `/metrics/resource`, which provide resource utilization metrics about the containers themselves.
A separate commit for this PR will add prebuilt dashboards for these new metrics.
See also #1070

ui: add container metrics scrape targets to K8s metrics integration

---

.buildkite/pipeline.yml
ci/test-upgrade/fetch-cli-artifacts.sh

As discussed in slack:
> I propose running the upgrades pipeline (for GCP only) in all PRs for the next two weeks. This way, we can quantify how much it affects developer productivity.

ci: run upgrade tests on GCP as part of PR pipeline

---

.buildkite/pipeline.yml
ci/test-upgrade/fetch-cli-artifacts.sh

* Use the latest available release from https://go.otr.dev/cli-latest-release-linux as the initial cluster.
* Fetch CLI artifacts hosted by HTTP servers.

ci(upgrades): change initial cluster version

---

packages/controller/src/resources/redis/index.ts

Happened to noticed it in the 'default' namespace.

controller: add namespace to 'redis-slave' service

---

packages/app/src/client/views/login/index.tsx

Minor cleanup of useEffect
> If you want to run an effect and clean it up only once (on mount and unmount), you can pass an empty array ([]) as a second argument. - [react-docs](https://reactjs.org/docs/hooks-effect.html#tip-optimizing-performance-by-skipping-effects)

ui: minor cleanup

---

lib/utils/src/buildinfo.ts

After feedback from the team. Sorry for the hassle.
This reverts the patch which brought in a dependency on the NODE_ENV environment variable (this brought its own complications,  as reported by @MoSattler).

buildinfo: better error msg for local dev

---

packages/controller-config/src/docker-images.json

The [cortex-operator](https://github.com/opstrace/cortex-operator/pull/14) by default enables Cortex api response compression. This setting got lost in the transition.
Testing if we see any impact to recent issues in #1107.

bump: cortex-operator 3318f7bf9-ci

---

test/test-remote/test_alerts.ts

CC @nickbp 
motivated by https://github.com/opstrace/opstrace/issues/1102#issuecomment-887405723
It's unclear why certain HTTP requests are not responded to in a timely fashion (below 10 s). This is fishy, we should investigate.

test-remote: test_alerts: bump timeout for waitForCortexMetricResult()

---

packages/app/src/client/app.tsx
packages/app/src/client/components/withSession/index.tsx
packages/app/src/client/views/cluster-config/index.tsx
packages/app/src/client/views/cluster-config/opstrace.tsx
packages/app/src/server/routes/api/authentication.ts
packages/app/src/state/cortex-config/hooks/useCortexConfig.ts
packages/app/src/state/opstrace-config/actions.ts
packages/app/src/state/opstrace-config/hooks/useOpstraceConfig.ts
packages/app/src/state/opstrace-config/reducer.ts
packages/app/src/state/opstrace-config/types.ts
packages/app/src/state/reducer.ts

important: depends on https://github.com/opstrace/opstrace/pull/1115 being merged first
I've added a second tab to the Cluster Admin -> Configuration section called Opstrace that shows the static Build Info. I envision this section growing over time and some future addions being user adjusted.

[wip] ui: Show Opstrace Build Info in app

---

packages/app/src/client/integrations/k8sLogs/Show/UninstallInstructions.tsx
packages/app/src/client/integrations/k8sMetrics/Show/UninstallInstructions.tsx

possibly related: https://github.com/opstrace/opstrace/issues/1098

ui: when uninstalling an i9n always deletes the grafana folder, don't need to do it in callback

---

packages/app/src/client/components/withSession/index.tsx
packages/app/src/server/routes/api/authentication.ts

Trying this again now that we're only creating a user session once per worker+browser rather than on every individual test. ie we're not hammering auth0 heaps anymore.

ui: back to express server determining user email via the /userinfo auth0 endpoint

---

go/pkg/middleware/proxy.go

https://pkg.go.dev/net/http#Header.Add
https://pkg.go.dev/net/http#Header.Set
> Set sets the header entries associated with key to the single element value. It replaces any existing values associated with key.
We want to take full control in the proxy, and set the header based on the value provided by the authenticator. Any value set by the original HTTP client should be obliterated. Therefore, use `Set()`.
Exploiting this for cross-tenant data writing would still require valid authentication proof for a tenant.

go: proxy: replace X-Scope-OrgID header

---

commitlint.config.js

Towards writing release notes, commit message prefixes should become more reliable.
This
* adds the `test-browser` prefix because it has become a real thing; CC @terrcin please use that :-).
* removes prefixes we have not used at all or not really used.
* removes prefixes we have mainly used 'wrongly' (such as 'fix').
* tries to sharpen the meaning of various component-based prefixes.
As always this state is evolving... I just wanted to have a little bit of an improvement now that we're in the release notes game.

Commit message prefix consolidation / simplification

---

packages/controller-config/src/resources/controller.ts

This is creating a log file with several gigabytes which eventually triggers a pod eviction when the node where the opstrace controller pod is running reaches disk pressure.
Close #1152.

chore: disable nodejs profiler

---

packages/app/src/client/views/ring-health/RingHealth.test.tsx
packages/app/src/client/views/ring-health/RingTable.tsx

Fixing this [error reported by sentry](https://sentry.io/organizations/opstrace/issues/2535043152/?environment=production&project=5529515&query=is%3Aunresolved):
The underlying problem was that while we handle errors in the response, we did not handle errors on the request level (e.g. no network connection). 
I believe this might be an issue we could potentially run into many places where we do requests.

fix(RingTable): error handling

---

ci/test-cli/cli-tests-with-cluster.sh
lib/utils/src/docker.ts
packages/cli/src/index.ts
packages/cli/src/info.ts
packages/controller-config/package.json
packages/controller-config/src/index.ts
packages/controller-config/src/resources/controller.ts
packages/controller-config/src/schema.ts
packages/controller-config/src/schemav3.ts
packages/installer/src/index.ts
packages/upgrader/src/index.ts
packages/upgrader/src/upgrade.ts
yarn.lock

`opstrace info <aws|gcp> <cluster name>` will print Opstrace and Kubernetes cluster info in the following format:
```
cluster info:
cluster_version: <kubernetes version>
controller_version: <image tag>
installer_version: <installer commit string>
```
Installer version is stored in the controller's configmap and updated on each upgrade event, while other version information is read from k8s cluster configuration at runtime.
Closes #454
Might also address part of #1023
/cc @sreis

feat(cli,config): info command prints stored/read cluster metadata

---

packages/controller-config/src/docker-images.json

https://github.com/grafana/loki/compare/1ed19f7...138ca71

bump: loki to 138ca71

---

packages/controller-config/src/docker-images.json

https://github.com/cortexproject/cortex/compare/fde0a62...a4bf103
91 commits, since May 20.
This will btw be pretty much the 1.10.0 release.

bump: cortex to a4bf103

---

packages/app/src/client/components/Form/SelectInput.tsx
packages/app/src/client/integrations/k8sLogs/Form.tsx
packages/app/src/client/integrations/k8sLogs/Show/index.tsx
packages/app/src/client/integrations/k8sLogs/Show/templates/config.ts

Adds an option for specifying whether the cluster is running CRI/containerd or dockerd. This is required by the underlying log scraper - depending on the runtime, the paths for the data are different and they have totally different formats. Previously, the code was hardcoded to CRI/containerd even though the underlying yaml template had an option for dockerd. There was just a TODO for exposing this as an option.
The result looks like this. Could probably be cleaned up a bit but I figured that this should be okay for now (baby's first react UI):

ui: Add radio option for log format to K8s log integration

---

docs/manifest.json
packages/app/src/client/integrations/common/UninstallIntegrationBtn.tsx
packages/app/src/client/integrations/k8sLogs/Show/InstallInstructions.tsx
packages/app/src/client/services/Notification/NotificationService.test.tsx
packages/app/src/client/services/Notification/NotificationService.tsx
packages/app/src/client/views/ring-health/RingTable.tsx

The current notification hook has a [quiet verbose interface and is not straightforward to use](https://github.com/opstrace/opstrace/blob/b04440718010e7e13c7f4856bdbb995b5588bc61/packages/app/src/client/integrations/common/UninstallIntegrationBtn.tsx#L66-L78). 
So far most use cases have been very similar without the need of having a super configurable notification system. 
Here I am adding a small wrapper called `useSimpleNotification` that turns this:
```typescript
const id = generateId();
registerNotification({
id,
state: "error" as const,
title: "Could not delete grafana folder",
information: error.message,
handleClose: () =>
unregisterNotification({
id: messageId,
title: "",
information: ""
})
});
```
into this
```typescript
registerNotification({
state: "error" as const,
title: …
```

ui(NotificationService): simpler interface

---

ci/test-core.sh

ci: sleep before test-remote (instability #944)

---

.gitignore
test/browser/README.md
test/browser/fixtures/authenticated.ts
test/browser/package.json

this allows Playwright to reuse user session state between runs on local dev machine to limit login attempts. refer to the updated readme for how to use it.

test-browser: toggle for saving/loading Playwright state between runs

---

ci/scripts/cleanup-cloud-dns.sh

Adds a script to clean up GCP Cloud DNS zones leftover by CI.
I'm currently running it locally to cleanup ci-shard-eee and this is an example output:
```
deleting record set dd.treetops792.upgrade-bk-1138-664-g.opstrace.io. TXT
Deleted [https://dns.googleapis.com/dns/v1/projects/ci-shard-eee/managedZones/upgrade-bk-1138-664-g-opstrace-io/rrsets/dd.treetops792.upgrade-bk-1138-664-g.opstrace.io./TXT].
deleting record set loki.treetops792.upgrade-bk-1138-664-g.opstrace.io. A
Deleted [https://dns.googleapis.com/dns/v1/projects/ci-shard-eee/managedZones/upgrade-bk-1138-664-g-opstrace-io/rrsets/loki.treetops792.upgrade-bk-1138-664-g.opstrace.io./A].
deleting record set loki.treetops792.upgrade-bk-1138-664-g.opstrace.io. TXT
Deleted [https://dns.googleapis.com/dns/v1/projects/ci-shard-eee/managed …
```

ci: add a script to clean up gcp cloud dns zones

---

lib/dns/src/index.ts
packages/uninstaller/src/gcp.ts

The DNS zone name was missing a dot '.' at the end. The uninstaller now uses the same code as the installer to generate the DNS zone name.
Close #1195

cli(destroy): correctly delete gcp dns managed zone

---

packages/cli/src/list.ts

Follow-on from #1193.
AWS announced the Osaka region on March 1, 2021.  Add this explicitly to our list of supported regions.
https://aws.amazon.com/blogs/aws/aws-asia-pacific-osaka-region-now-open-to-all-with-three-azs-more-services/

cli: add support for new ap-northeast-3 aws region

---

.buildkite/pipeline.yml

With the workaround https://github.com/opstrace/opstrace/pull/1220 being in place we can revert this change here.

ci: pr pipeline: upgr test: revert FROM change

---

lib/utils/src/deadline.ts
lib/utils/src/httpclient.ts
packages/app/package.json
packages/app/src/server/routes/api/authentication.ts
packages/app/src/server/routes/api/jwks.ts
packages/app/src/server/server.ts
packages/app/tsconfig.json
yarn.lock

This is to enhance login robustness by a great deal
This PR implements this:
> perform retrying around JWKS fetching requests. As a bonus, try to populate the JWKS cache upon app start, i.e. not as part of processing an HTTP request.
quote from https://github.com/opstrace/opstrace/issues/1156.
on top of the cache implemented in `jwksRsa.expressJwtSecret()` this adds:
*  A custom JWKS HTTP endpoint fetch function using the got() HTTP client with carefully chosen retrying parameters and logging.
* A use-stale-item-if-refresh-failed technique for making the cache more useful and robust.
* A prepopulate-upon-app-start technique to make the first login more robust and fast (minimize hot path impact).

UI login: make JWKS fetching more robust

---

packages/controller-config/src/docker-images.json

Bump Cortex by 11 commits., a little beyond the 1.10.0 release.
Two commits with payload:
https://github.com/cortexproject/cortex/commit/4405f9c339779b5861f5755bd867ee7bac4f4fa9
https://github.com/cortexproject/cortex/commit/7133f01763e892430b97f3b440e0df11e88c16dc

cortex: use current head of master

---

.gitignore
packages/app/src/client/views/ring-health/RingHealth.tsx
packages/app/src/client/views/ring-health/RingTable.tsx
packages/app/src/client/views/ring-health/cortex/index.tsx
packages/app/src/client/views/ring-health/testUtils.ts
test/browser/fixtures/authenticated.ts
test/browser/package.json
test/browser/tests/clusterHealth.spec.ts
test/test-remote/test_ui_api.ts

White doing change I noticed that there was an `await` [missing](https://github.com/opstrace/opstrace/pull/1184/files#diff-0d2fcdddb14264ab274aba532f31800e276351ccf562e3e5ed4dcc72ac30fb73L608) from the original test-remote test which _may_ have been causing the problems on CI. The test should be under browser-test so I moved and corrected the problem.

test-browser: migrate in the ring health test to help stabilise CI

---

lib/kubernetes/src/reconciliation/reconcile.ts

We want the logs to periodically report when something isn't being managed by the controller.
This ensures that "periodically" means every 5 minutes rather than every 5 seconds.

controller: don't flood 'Leaving x as-is' when opstrace annotation is removed

---

packages/controller-config/src/docker-images.json

Bump Loki by six commits: https://github.com/grafana/loki/compare/138ca71...f5fd029
f5fd029 corresponds to the 2.3.0 release.

loki: use 2.3.0 release

---

packages/upgrader/src/index.ts
packages/upgrader/src/upgrade.ts

Close #1223
Move the buildinfo version check to as early as possible and checks if the `cliMetadata.allCLIVersions` image tag of the Opstrace controller deployment matches the one defined in the CLI buildinfo. Older Opstrace versions will have an empty cliMetadata field, for these, check the Opstrace controller deployment image and check it matches buildinfo.

cli(upgrade): exit early if buildinfo matches

---

Makefile
test/browser/README.md
test/browser/fixtures/authenticated.ts
test/browser/package.json
test/browser/run_on_ci.sh
test/browser/tests/authentication.spec.ts

This change updates how the playwright browser tests are executed on CI. the `OPSTRACE_PLAYWRIGHT_REUSE_STATE` env var is now set to `true` which means that the login fixtures and hooks will look for and use a previously logged in state (file on disk), if it's not there a normal login will occur and then the logged in state will be saved. 
On CI playwright is now run twice, once with a single worker running a single test that logs the user in resulting in the logged in state being saving to disk. The second and main run is now back to using multiple workers each reusing the logged in state rather than logging in. This means we can have any number of workers and only login once per test run.

[wip] test-browser: run single auth spec to save logged in state before executing the entire suite which reuses it

---

ci/deploy-testremote-teardown.sh

The GCP project `ci-shard-eee` has been exhibiting #293 more frequently than the other projects.  Let's remove it from rotation for now.

chore: remove shard-eee based (see #293)

---

packages/app/.env.client.development.example
packages/app/.env.server.development.example
packages/app/config/env.js
packages/app/package.json
packages/app/src/client/index.tsx
packages/app/src/client/serviceWorker.ts
packages/app/src/server/env.ts
packages/app/src/server/routes/api/authentication.ts
packages/app/src/server/routes/api/uicfg.ts
packages/app/src/server/server.ts
packages/app/src/state/opstrace-config/reducer.ts
yarn.lock

Now by default exceptions won't be sent to Sentry from the React app, this can be overriden with an env var. Additionally I've added Sentry exception tracking to the Express server and include BUILD_INFO data in the metadata tags sent from both server and client.

ui: do not load Sentry when running on localhost 

---

packages/upgrader/src/upgrade.ts

Noticed it while running upgrades locally.

cli: skip cortex ownership transfer if cortex-operator is installed

---

.buildkite/pipeline.yml

```
[2021-08-12T15:08:09Z] 2021-08-12T15:08:09.517Z error: cluster name must not be longer than 23 characters (is: 26)
[2021-08-12T15:08:09Z] 2021-08-12T15:08:09.517Z debug: shut down logger, then exit with code 1
```
https://buildkite.com/opstrace/scheduled-main-builds/builds/2843#0b430bbb-4380-4fd1-b036-90d671f4b570
This did not happen on the PR because the pipeline slug is longer for the scheduled builds.

ci: upgrade tests: fix cluster name length (broken scheduled build on `main`)

---

packages/controller/src/cmd.ts
packages/controller/src/resources/apis/systemlogs.ts
packages/controller/src/tasks/gke.ts

When the controller notices it's running on GKE 1.18+ the fluentd config will not include the CRI parser.
Couldn't find anything in the Kubernetes javascript client that would return the API server version. I had to improvise and resorted to querying the /version endpoint manually. So, when the controller runs the reconcile loop on GCP it will fetch the API server version and cache it locally to avoid spamming the API server when the reconcile loop runs. 
I tested this locally by creating an instance on GCP with the latest available release of Opstrace (GKE version 1.18) and upgrading Opstrace to the version built from this PR branch. 
Close #1254

controller: fix fluentd config on gke 1.18+

---

packages/app/src/client/components/withSession/index.tsx
packages/app/src/server/routes/api/authentication.ts

This is to enhance robustness, allowing for auto-healing short transient issues. Also motivated by CI instability #1249.

UI: retry login POST request to /_/auth/session

---

packages/app/src/client/components/withSession/index.tsx
packages/app/src/server/routes/api/authentication.ts
test/browser/Dockerfile
test/browser/package.json
test/test-remote/package.json
test/test-remote/test_ui_api.ts
yarn.lock

See commit messages and code comments (also those code comments that are being removed).
I tested the retrying logic locally by injecting failures here and there.

UI: retry GET request to /_/auth/status, consolidate state management around that & collect browser console in test-remote

---

.buildkite/pipeline.yml
Makefile
ci/preamble.sh

So far the CI container image was never pushed to docker hub.
It was bound to the lifetime of the VM / disk.
Sometimes, a build finds empty / fresh state (fresh disk) and then the CI container image needs to be built from scratch. This takes a few minutes. Can reduce the duration of that process by pulling in some image layers stored on docker hub. (the last N layers need to be built and pushed for each build, and that's at the _con_ side of this change -- let's monitor the impact).

ci: push/pull CI container image.

---

test/test-remote/test_alerts.ts

MIGHT be a workaround for #1130, where there may be a race condition between deleting an alerts config followed immediately by setting it.

test-remote: Check that alerts configs exist before sending delete requests

---

lib/kubernetes/src/readiness/statefulset.spec.ts
lib/kubernetes/src/readiness/statefulset.ts

When a Statefulset roll out is in progress the rollingUpdate.partition field is set to a number. The numbering however starts at 0 which makes the condition check return the empty string. The empty string signals the function caller the given Statefulset is ready.
Adds unit tests with full coverage for the `getStatefulSetRolloutMessage` function.
Close #1294

chore: fix readiness check

---

packages/controller/src/system/alerts.ts

Reenable when we introduce cortex ingester container memory limits.

chore: disable CortexAllocatingTooMuchMemory alert

---

ci/github-issue-labels.yaml

Trying to help with https://github.com/opstrace/opstrace/pull/1300.
See individual commit messages.
Instead of "add a labels area for alerts" I propose to add one for system monitoring so that this also includes dashboards etc.

github issue labels: update codetree-related labels, add `area: system-monitoring`

---

ci/test-upgrade/run.sh
ci/test-upgrade/teardown.sh
lib/gcp/src/globalAddress.ts

Workaround for #976. I think this is some undocumented behavior where a second request to [delete the global address](https://cloud.google.com/compute/docs/reference/rest/v1/addresses/delete) returns a 400.
The log output of a successful destroy operation shows the global desired state is reached immediately after the delete. 
```
[2021-08-24T00:53:20Z] 2021-08-24T00:53:20.930Z [32minfo[39m: Ensure Address deletion
[2021-08-24T00:53:21Z] 2021-08-24T00:53:21.124Z [32minfo[39m: Global Address is RESERVED
[2021-08-24T00:53:23Z] 2021-08-24T00:53:23.753Z [32minfo[39m: Global Address teardown: desired state reached
```
A failed run shows it tried to issue a delete twice.
```
[2021-08-23T19:04:24Z] 2021-08-23T19:04:24.724Z info: Global Address is RESERVED
[2021-08-23T19:04:27Z] …
```

cli(destroy): handle gcp global address tear down

---

ci/invoke-looker.sh
test/test-remote/README.md
test/test-remote/looker/package.json
test/test-remote/looker/src/args.ts
test/test-remote/looker/src/index.ts
test/test-remote/looker/src/logs/dummystream.ts
test/test-remote/looker/src/metrics/dummyseries.ts
test/test-remote/looker/src/prommetrics.ts
test/test-remote/looker/src/series.ts
test/test-remote/looker/src/util.ts
test/test-remote/test_prom_remote_write.ts
test/test-remote/testutils/logs.ts

This was part 1: https://github.com/opstrace/opstrace/pull/1310
This PR continues implementing the coupling mechanism for Looker's 'log mode' but also brings along a number of significant behavioral changes that also affect the coupling in 'metric mode'.

looker: log series with synthetic time source coupled to wall time (part 2)

---

packages/app/src/client/views/users/AddUserDialog.test.tsx
packages/app/src/client/views/users/AddUserDialog.tsx

Improving the user feedback from previously:
To now:

ui(users): improve user creation hints

---

test/test-remote/test_loki_tail_endpoint.ts

Working on a fix in PR opstrace/opstrace#1340 but let's skip this one flaky test to reduce noise in the meantime.

chore: skip flaky loki tail endpoint test

---

ci/deploy-testremote-teardown.sh
ci/test-upgrade/run.sh

Currently unable to create SQL databases in ci-shard-aaa (possibly related to #293). Cycling out ci-shard-aaa in favor of ci-shard-dd.

ci: replace ci-shard-aaa with ci-shard-ddd

---

ci/deploy-testremote-teardown.sh
ci/test-upgrade/run.sh

This project seems to be hitting some hidden quota related to #1343. Remove it from rotation to get green CI again.

ci: remove ci-shard-iii from rotation

---

lib/aws/src/vpc.ts
lib/kubernetes/package.json
package.json
packages/cli/package.json
packages/cli/src/list.ts
packages/cli/src/ucc.ts
packages/controller/src/resources/ingress/externalDns.ts
packages/installer/src/aws.ts
packages/installer/src/index.ts
packages/uninstaller/src/aws.ts
test/browser/package.json
test/test-remote/looker/package.json
test/test-remote/package.json
yarn.lock

Plays it safe and pins to exactly 4.4.2 for now. Could go with 4.4.x instead?
The errors seen before in CI around catch types seems to indeed be a 4.4.x thing:
https://devblogs.microsoft.com/typescript/announcing-typescript-4-4-rc/#use-unknown-catch-variables

chore: misc typing fixes and a bump to TS 4.4.2 (latest)

---

packages/app/src/client/integrations/common/UninstallIntegrationBtn.test.tsx
packages/app/src/client/services/Notification/NotificationService.test.tsx
packages/app/src/client/services/Notification/NotificationService.tsx
packages/app/src/client/utils/testutils/testutils.tsx
packages/app/src/state/reducer.ts

In order to be able to raise notifications from stores and sagas (e.g. request error handling), the notification state needs to live in the main store, not in a separate one (as was before the case). 
Perquisite for #1333

ui(notifications): merge reducer into main store

---

packages/app/src/client/components/Error/View.tsx

It's a common misconception that `window.location.reload()` has a `boolean` parameter. This is not the case according to the spec. In fact, this flag is ignored by all browsers but firefox. [Read more about this on MDN](https://developer.mozilla.org/en-US/docs/Web/API/Location/reload#location.reload_has_no_parameter).
In firefox, the flag is to bypass its cache and force-reload the current document. If in fact this is something we want to do, we should look for a way that achieves this across all browsers. 
While `reload(boolean)` was [marked as deprecated](https://microsoft.github.io/PowerBI-JavaScript/interfaces/_node_modules_typedoc_node_modules_typescript_lib_lib_dom_d_.location.html#reload) for a long time, it seems like that TS compilation entirely fails now if it's used (see …

ui(error-view): fix wrong reload call

---

ci/test-upgrade/fetch-cli-artifacts.sh

~For curl, 3 retry attempts with a 10s delay between them seemed like reasonable numbers.~ (Forgot we had curl wrapper for retries in ci/utils.h) AWS cli doesn't seem to have an option to set the delay between retries.
Close #1357

ci: retry cli artifact download

---

packages/controller/src/resources/cortex/index.ts
packages/controller/src/resources/loki/index.ts

While triaging for #1226 I saw the following error printed by loki querier:
```
msg="error processing requests" address=X.X.X.X:9095 err="rpc error: code = Unknown desc = closing transport due to: connection error: desc = \"error reading from server: EOF\", received prior goaway: code: ENHANCE_YOUR_CALM, debug data: too_many_pings"
```
Some googling later and I found the following PRs to tweak the grpc keepalive config:
https://github.com/grafana/cortex-jsonnet/pull/233
https://github.com/grafana/loki/pull/4182/files

loki|cortex: tweak grpc settings

---

packages/controller/src/system/alerts.ts

1. Increase absolute network traffic threshold.
2. Increase CPU utilization threshold.
3. Ignore `opstrace-controller-*` pods in the `KubePodNotReady` alert; the Kubernetes apiserver won't garbage collect the failed pod resources because the opstrace-controller deployment owns everything.

alerts: minor tweaks to alert settings

---

test/test-remote/looker/src/metrics/dummyseries.ts

looker: fix metrics mode with one sample per fragment

---

lib/aws/src/launchConfiguration.ts
packages/controller/src/resources/loki/index.ts

Back in https://github.com/opstrace/opstrace/issues/1226#issuecomment-915346058, we saw that the S3 bucket list request was stalling for 2+ minutes. It turns out it was one of the requests, an `ec2metadata/GetToken` that makes a `PUT /latest/api/token HTTP/1.1`, that was hanging. This led me to find https://github.com/aws/aws-sdk-go/issues/2972, which mentions that containers running on EC2 instances have issues accessing the AWS instance metadata endpoint due to a network knob not being configured properly.
I've ran a build in the draft PR #1351 with this fix applied and the stalling AWS instance metada requests seems to be fixed.
A few notes from that [build](https://buildkite.com/opstrace/prs/builds/5774#21a0e0fe-ed01-4710-8f9c-4fb1fd6bcfa7/5538-7453):
1) The installer no longer times …

fix: increase hop limit to access AWS instance metadata endpoint

---

ci/cluster-config.yaml
ci/test-upgrade/initial-cluster-config.yaml
docs/references/configuration.md
packages/cli/src/schemas.ts
packages/cli/src/schemasv2.ts
packages/cli/src/ucc.spec.ts
packages/cli/src/ucc.ts
packages/cli/src/upgrade.ts
packages/config/src/clusterconfigv2.ts
packages/controller-config/src/schemav2.ts
packages/controller-config/src/schemav3.ts
packages/controller/src/resources/app/app.ts
packages/installer/src/index.ts
packages/upgrader/src/index.ts
packages/upgrader/src/upgrade.ts

The `custom_auth0_domain` parameter logically accompanies `custom_auth0_client_id`.
`custom_auth0_client_id` was not generally functional w/o the domain parameter.
Also see https://github.com/opstrace/opstrace/issues/1175
Tested config validation with an intentionally bad config:
```
± node packages/cli/build/index.js create aws rofl -c cluster-config.yaml 
2021-09-08T14:42:30.744Z info: logging to file: opstrace_cli_create_20210908-144230Z.log
2021-09-08T14:42:30.746Z info: Discovered AWS credentials. Access key: AKIA...AOGY
2021-09-08T14:42:30.763Z error: invalid config document: 'custom_auth0_client_id' requires 'custom_auth0_domain' and vice versa
```

instance config: add custom_auth0_domain parameter

---

packages/controller/src/system/alerts.ts

Noisy, currently unhelpful alert. 
See commit message:  https://github.com/opstrace/opstrace/commit/be52bea147e392998e2212863f414aecfc5df784

alerts: temporarily disable CortexProvisioningTooManyWrites

---

test/test-remote/looker/src/logs/dummystream.ts
test/test-remote/testutils/logs.ts

Note that the response containing the errant body is already being logged, this just adds a retry.
Seen in CI flake: https://buildkite.com/opstrace/scheduled-main-builds/builds/3086

test-remote: log/retry query if loki returns a 500 error with error text

---

lib/aws/src/autoScalingGroup.ts

This is executed as part of an upgrade, in particular
as part of the 'infrastructure upgrade'.
When this runs, EC2 instance metadata is mutated
so that HttpPutResponseHopLimit is set from 1 (the
default to 2). This is a pragmatic first step
#1383.
Note that this per-instance mutation is not
persistent: goes away when an intance goes away
in an auto-scaling group.
To persist this kind of configuration change
the underlying launch configuration needs to
be mutated (more context in #1383).

cli: aws infra setup: set ec2 instance metadata (wip)

---

ci/test-upgrade/initial-cluster-config.yaml

This is to address https://github.com/opstrace/opstrace/issues/1405. An expected change after the last release. Just forgot about that right after the release.

ci: upgr test init cfg: add auth0 param (fix #1405)

---

ci/utils.sh

Makes the output more verbose, hopefully showing the content of the certs.
Hopefully will help with tracking down #1388, where checks are getting generic "unable to load certificate" errors but we aren't seeing what content is failing to be loaded.

ci: log cert/issuer content when checking LE certs

---

go/cmd/cortex/main.go
go/cmd/cortex/proxy_test.go
go/pkg/middleware/proxy.go

When cortex is backing up (e.g. full distributor queues) it can return 500 errors.
If clients retry-loop on these errors, it can lead to nobody being able to catch up.
Note that this is separate from the existing 429->503 mapping, which stays as-is.
See also https://github.com/opstrace/opstrace/issues/1409

cortex: remap 'retryable' 5xx errors to non-retryable errors

---

lib/dns/src/opstrace.ts
yarn.lock

Tested with mock service and in real world, trigger-login-upon-401 works again, tested during `opstrace create ...`:
```
2021-09-24T14:36:28.353Z info: setting up DNS
2021-09-24T14:36:29.258Z warning: DNS service client:GET failed: Response code 401 (Unauthorized)
2021-09-24T14:36:29.259Z info: perform another login to refresh authentication state
2021-09-24T14:36:29.259Z info: initiate device code login against https://opstrace-dev.us.auth0.com
```
This workaround should fix #1323. It is pretty sad that I do not understand the exact nature of this error handling problem.
It is unclear how the regression entered the system.

cli: dns service http client: work around err handling regression #1323 (includes: trigger-login-upon-401)

---

docs/references/configuration.md

Adding missing data retention parameters:  `log_retention_days` and `metrics_retention_days`.

chore: add missing reference for data retention parameters

---

yarn.lock

Updating ssri in the dep tree to address https://github.com/advisories/GHSA-vx3p-948g-6vhq

chore: update ssri npm package

---

packages/app/package.json
yarn.lock

Removes `glamor`, as it seems that we do not use that package.
Addresses https://github.com/advisories/GHSA-w7rc-rwvf-8q5r. 
Blocked by https://github.com/opstrace/opstrace/pull/1432

chore: remove glamor

---

packages/app/package.json
yarn.lock

Addresses https://github.com/advisories/GHSA-hwj9-h5mp-3pm3 and [CVE-2021-23382](https://nvd.nist.gov/vuln/detail/CVE-2021-23382#vulnCurrentDescriptionTitle)

chore: update postcss and resolve-url-loader

---

packages/app/package.json
yarn.lock

Signed-off-by: Mo Sattler <hi@mosattler.com>
We do rely on "dotenv-expand", e.g. [here](https://github.com/opstrace/opstrace/blame/f0fd22918137b6eb351d4b15113a9911270ce5e6/packages/app/config/webpack.server.config.js#L58).
Though, we never have added it to the dependency lists, and it merely worked because storybook was coincidently shipping with this dependency. So [removing storybook](https://github.com/opstrace/opstrace/pull/1432) broke this code. 
This PR adds `dotenv-expand` explicitly to the dependency lists and fixes the issue above.

ui: fix missing dependency

---

package.json
yarn.lock

Forcing the `hasura-cli@1.3.3` dependency to use an updated `axios@0.21.1`, as it's required `axios@0.19.1` has the known vulnerability https://github.com/advisories/GHSA-4w2v-q235-vp99.
While this version of axios is technically out of [`hasura-cli@1.3.3` specified range](https://github.com/jjangga0214/hasura-cli/blob/v1.3.3/package.json#L94), this update should be safe, because:
1. The version bump [does NOT contain any breaking changes](https://github.com/axios/axios/blob/master/CHANGELOG.md).
1. [`axios` is NOT extensively used by `hasura-cli`](https://github.com/jjangga0214/hasura-cli/search?q=axios)
Though, this change should be seen as a hot fix. The proper way of achieving a safe version of `Hasura-cli/axios` would be to update `hasura-cli@1.3.3` to `hasura-cli@>2`, where this …

chore: update hasura-cli/axios

---

go/README.md
go/go.mod
go/go.sum
go/pkg/authenticator/jwt.go
go/pkg/authenticator/keyset_test.go
go/pkg/authenticator/testresources.go
go/pkg/ddapi/handler_test.go

from https://github.com/dgrijalva/jwt-go to https://github.com/golang-jwt/jwt
https://github.com/golang-jwt/jwt/blob/main/MIGRATION_GUIDE.md
Added tests for more confidence that this does not introduce an embarrassing security regression.

go authenticator: migrate to jwt lib v4

---

.buildkite/pipeline.yml
ci/deploy-testremote-teardown.sh
packages/cli/src/schemas.ts
packages/cli/src/schemasv2.test.ts
packages/cli/src/schemasv2.ts
packages/cli/src/ucc.spec.ts
packages/cli/src/ucc.ts
packages/config/src/clusterconfigv2.ts
packages/controller/src/resources/app/app.ts
packages/installer/src/aws.ts
packages/installer/src/gcp.ts
packages/installer/src/index.ts
packages/uninstaller/src/index.ts
packages/upgrader/src/upgrade.ts

Changelog of changes in the branch:
* Require the `custom_dns_name`, `custom_auth0_client_id`, and `custom_auth0_domain` parameters to be set when creating/upgrading an instance.
* Change AWS CI job to use a custom DNS name in the `opstraceaws.com` root domain.
* Create a hosted zone in Route53 for the new instance.
* Add an NS entry in the opstraceaws.com root zone for the new instance hosted zone.
* On teardown, delete the instance hosted zone and remove the NS entry in the `opstraceaws.com` root zone.
* Disables upgrade tests in CI PR pipeline because it does not support running with a custom domain name. 
**NOTE**
*After merging the PR, we need to disable the scheduled upgrade tests because that pipeline does not support custom domain names.*

chore: AWS custom DNS name

---

docs/references/configuration.md

Reported in community slack but forgot to address it sooner.

docs: fix metric_retention_days typo
