ci/deploy-testremote-teardown.sh

Fix #86 
Add a retry to the certificate check because it can take a few seconds for the certificate to be used after it's marked ready.
This is a workaround to make CI happy. We should discuss if we want to do it in the the installer instead to ensure the cluster is marked ready only when the certificate is used correctly.

chore: retry certificate check

---

.markdownlint.json
README.md
ci/check-if-docs-pr.sh
docs/README.md
docs/quickstart.md

Some users found some broken links, and in the process I found some other issues.
It's worth noting that one user found a broken link that is known to be broken and cannot yet be fixed—we're waiting for GH to graciously approve our request to have repo-level discussions.  Using it in other repositories has been great, and we hope it will foster great dialog to help build up a community.

docs: more post-launch adjustments

---

ci/check-if-docs-pr.sh

Close #93
Tested locally by running the script.
This is the output of a docs only PR:
```
> BUILDKITE_PULL_REQUEST=92 bash ./ci/check-if-docs-pr.sh
+ echo 'BUILDKITE_PULL_REQUEST: 92'
BUILDKITE_PULL_REQUEST: 92
+ '[' -z 92 ']'
+ '[' 92 = false ']'
++ curl --silent -H 'Accept: application/vnd.github.v3+json' https://api.github.com/repos/opstrace/opstrace/pulls/92/files
++ jq -r '.[].filename'
+ FILES_EDITED_IN_PR='.markdownlint.json
README.md
ci/check-if-docs-pr.sh
docs/README.md
docs/quickstart.md'
+ ALLOWLIST='^docs/|.gitattributes|^.github|^README.md|^.markdownlint.json'
++ echo .markdownlint.json README.md ci/check-if-docs-pr.sh docs/README.md docs/quickstart.md
++ egrep -v '^docs/|.gitattributes|^.github|^README.md|^.markdownlint.json'
++ tr -d '[:space:]'
+ DOCS_ONLY_CHANGES=
+ '[' …
```

chore: improve docs only pr check

---

docs/quickstart.md

Signed-off-by: Chris Lambert <chris@opstrace.com>

docs(quickstart): fix broken link (missing .md)

---

ci/check-if-docs-pr.sh
ci/deploy-testremote-teardown.sh
ci/publish-artifacts.sh
ci/utils.sh

Follow up to [this review request](https://github.com/opstrace/opstrace/pull/94#discussion_r535627347).

fix: retry curl command on transient errors

---

packages/controller-config/src/docker-images.json

Good / interesting commits to have:
- https://github.com/cortexproject/cortex/commit/77164918c0d7541d8fbc4d0c6062a0cc71d0a5a9
- https://github.com/cortexproject/cortex/commit/bdcbb0397f174b9001dc906ad1b69c2e39874ab7
- https://github.com/cortexproject/cortex/commit/666719c1779ebd3d6a82f73b05f267d5ff6ff38a
- https://github.com/cortexproject/cortex/commit/60bc27069b262f308af5d27665a6ee35c315275d
- https://github.com/cortexproject/cortex/commit/49bbf39f5581c1b6e887c013ca4d9cebdc591336
- https://github.com/cortexproject/cortex/commit/65c0761a76b07de032ff73db6f3fee666b29a7c1
- https://github.com/cortexproject/cortex/commit/08256a9b7a3ffb0747b25bc9d98e332d54bb462d
- https://github.com/cortexproject/cortex/commit/beddbff9650e40f908ff3e589489047933d52985
- …

bump: cortex to latest dev

---

packages/controller-config/src/docker-images.json

bump: grafana: 7.3.3 -> 7.3.4

---

ci/deploy-testremote-teardown.sh
packages/controller-config/src/docker-images.json

Interesting / good-to-have commits:
- https://github.com/grafana/loki/commit/9ba5753e253dc60a751848c1fa6352c1d905187c
- https://github.com/grafana/loki/commit/06a89ea0ee0a58df343c0a25ad954d36b69f626c
- https://github.com/grafana/loki/commit/ec725db9d0aee23d737106ad67b0ebb2f751e7d8
- https://github.com/grafana/loki/commit/ae9c4b82ec4a5d21267da50d6a1a8170e0ef82ff
- https://github.com/grafana/loki/commit/dcbfecf9e549f264e5c16b1eefbe1b4071e508c1
- https://github.com/grafana/loki/commit/854930e661ee566734e6502ddfb5f4ce08364d72
- https://github.com/grafana/loki/commit/315972409b58664bf55d8f24cc3bdde60548e50f
- https://github.com/grafana/loki/commit/c98dfa0da1599c290c5400edc12174d3aeb93338
- https://github.com/grafana/loki/commit/9807f7c43e4e46be367372d241a15406fdf89d19
- …

bump: loki to current head of master

---

lib/aws/src/util.ts

For #116. #69 did contain an oversight.

chore: aws-sdk-js: info-log some retries

---

docs/references/cluster-configuration.md

docs: cluster config ref: add aws.eks_admin_roles description (plus misc notes)

---

Makefile
ci/preamble.sh
containers/ci/opstrace-ci.Dockerfile
docs/guides/contributor/workflows.md
lib/utils/src/diff.ts
package.json

Will also address https://github.com/opstrace/opstrace/issues/73.
todo:
- fix the problems that it finds
- remove the yarn entry points
- document

ci: perform license headers check across entire repo

---

packages/controller/src/resources/cortex/index.ts
packages/controller/src/resources/loki/index.ts

fix: bring up loki and cortex statefulset services in order

---

packages/app/package.json
packages/app/src/client/index.tsx
packages/installer/src/informers.ts
yarn.lock

Add sentry

---

ci/deploy-testremote-teardown.sh
packages/cli/src/create.ts
packages/cli/src/index.ts
packages/cli/src/status.ts
packages/installer/src/index.ts

Work for https://github.com/opstrace/opstrace/issues/146.

cli: --write-kubeconfig-file (asap), ci: send logs asap (wip)

---

ci/deploy-testremote-teardown.sh
docs/quickstart.md

@triclambert I hope the quick start changes are largely uncontroversial. Going ahead with this.

ci: log gcp project, docs: a few quickstart fixes

---

.buildkite/pipeline.yml
Makefile
ci/deploy-testremote-teardown.sh
ci/publish-artifacts.sh

ci: pull check-if-docs-pr.sh into pipeline

---

ci/deploy-testremote-teardown.sh
packages/cli/src/status.ts
packages/installer/src/index.ts

See https://github.com/opstrace/opstrace/issues/114#issuecomment-743199902

ci: check certificate for data api endpoint load balancer

---

docs/README.md
docs/quickstart.md
docs/references/roadmap.md

See #2128.
Also, see Google Analytics.

docs: address user feedback and behavior

---

packages/app/src/client/services/Picker/PickerService.tsx
packages/app/src/client/services/Picker/__tests__/PickerService.test.tsx

Loop through picker list

---

packages/app/src/client/services/Command/CommandPicker.ts
packages/app/src/client/services/Command/CommandPicker.tsx
packages/app/src/client/services/Command/__tests__/util.test.tsx
packages/app/src/client/services/Command/util.ts
packages/app/src/client/services/Picker/PickerService.tsx
packages/app/src/client/services/Picker/types.ts

Show keybindings for commands

---

ci/dns_cache.sh

ci: acquire lock only in linux systems

---

lib/utils/package.json
lib/utils/src/deadline.ts
lib/utils/src/diff.ts
lib/utils/src/file.ts
lib/utils/src/index.ts
lib/utils/src/log.ts
lib/utils/src/math.ts
lib/utils/src/sagas.ts
lib/utils/src/time.ts

Fix lint in lib directory (wip)

---

lib/dns/src/opstrace.ts

Among others, this addresses https://github.com/opstrace/opstrace/issues/124.

CLI: consolidations in dns client 

---

.github/workflows/docs-sync.yml

docs(sync): select correct version for sync

---

.gitignore
Makefile

makefile: remove yarn install speedup

---

packages/app/src/client/components/SplitPane/SplitPane.tsx
packages/app/src/client/layout/MainContent.tsx
packages/app/src/client/services/Display/DisplayService.tsx
packages/app/src/client/services/Display/reducer.ts

Save sidebar width in DisplayService

---

lib/utils/package.json
packages/app/package.json
yarn.lock

Fix https://github.com/advisories/GHSA-4w2v-q235-vp99

chore: bump axios to 0.21.1 to fix CVE

---

packages/app/src/client/views/login/index.tsx

This improves upon https://github.com/opstrace/opstrace/issues/243

ui: login view: hide button in sso flow, tweak "login" vs. "log in"

---

ci/deploy-testremote-teardown.sh

ci: gcp: no aaa yes bbb

---

ci/check-deployed-docker-images.sh
ci/deploy-testremote-teardown.sh
ci/preamble.sh
test/test-remote/test_ui.ts

Fix #247 
Adds a test to check if the list of docker images in docker-images.json was deployed to the cluster.

ci: fix controller image build

---

docs/guides/contributor/workflows.md

docs: incorrect path to writing-docs

---

packages/controller/src/resources/monitoring/system/dashboards/opstrace-overview.json

feat: add opstrace system overview dashboard

---

test/test-remote/package.json
yarn.lock

Try to address #275 (playwright setup error)

---

go/pkg/ddapi/handler.go
go/pkg/ddapi/handler_test.go
go/pkg/ddapi/testutil.go
test/test-remote/nodejs-testrunner.Dockerfile

Also, try to fix unrelated #280.

DD API: tweak behavior, work on unit test scaffold, add unit tests

---

go/pkg/ddapi/handler.go
go/pkg/ddapi/handler_test.go
go/pkg/middleware/authenticator.go
go/pkg/middleware/proxy.go
packages/controller/src/resources/apis/cortex.ts
packages/controller/src/resources/apis/dd.ts
packages/controller/src/resources/apis/index.ts
packages/controller/src/resources/apis/loki.ts

DD API: authenticator (WIP)

---

docs/guides/contributor/workflows.md

docs(writing): fix code format, add details for local controller

---

.buildkite/test-upgrade-pipeline.yml
Makefile
ci/deploy-testremote-teardown.sh
ci/test-upgrade/create-cluster.sh
ci/test-upgrade/dns-service-credentials.sh
ci/test-upgrade/fetch-cli-artifacts.sh
ci/test-upgrade/run.sh
ci/test-upgrade/teardown.sh
ci/test-upgrade/upgrade-cluster.sh
ci/utils.sh
commitlint.config.js
test/test-remote/nodejs-testrunner.Dockerfile

Close #267
I'll follow up with tickets for:
- How to manage flaky tests in main branch when the test remote fails before running the upgrade?
- Schedule upgrade tests that run after main branch tests

ci: add test upgrade pipeline to main branch

---

.github/workflows/link-check.yml

Run the [markdown link check](https://github.com/marketplace/actions/markdown-link-check) action on each Pull Request that modifies docs.

ci: link check

---

.markdownlint.json
docs/quickstart.md

docs: add quickstart video

---

.github/workflows/link-check.yml

Minor adjustment to the link-check action, [based on the comments](https://github.com/opstrace/opstrace/pull/316#issuecomment-770822032)

ci: adjust link check to run on docs changes only, reduce verbose mode

---

go/pkg/ddapi/testutil.go
go/pkg/ddapi/translate.go
packages/installer/src/index.ts
test/test-remote/test_dd.ts

DD API: sample inversion for the win

---

packages/controller-config/src/docker-images.json

Try to address #151 increased failure rates.

bump: cert-manager v1.1.0

---

go/pkg/ddapi/translate.go

Largely based on the discussion in #329.

DD API: consolidate label translation

---

go/Makefile
go/cmd/graphql/README.md
go/cmd/graphql/main.go
go/cmd/graphql/types.go
go/pkg/graphql/access.go
go/pkg/graphql/credential.go
go/pkg/graphql/exporter.go

graphql: Add authn, validate type mismatch, reduce access boilerplate

---

Makefile
ci/test-upgrade/create-cluster.sh
ci/test-upgrade/upgrade-cluster.sh

Part of #343 and tested locally.

test-upgrade: introduce upgrade command

---

docs/references/aws.md

docs: add minimum permissions to manage cluster on aws

---

test/test-remote/test_dd.ts

sad tmp fix for https://github.com/opstrace/opstrace/issues/393.

test-remote: tmp-disable test as of #393

---

packages/app/src/client/views/cluster/Sidebar.tsx

closes https://github.com/opstrace/opstrace/issues/395

temporarily disable tenant creation in ui

---

test/test-remote/test_dd.ts

test-remote: relax log needle check (#405)

---

packages/controller-config/src/docker-images.json
packages/controller/src/resources/cortex/index.ts
packages/controller/src/resources/monitoring/system/dashboards/cortex-overview-per-tenant.json

Also see
https://github.com/cortexproject/cortex/commit/7273defebca2783248a22ae1bc87b9c9abe5d54e
https://github.com/cortexproject/cortex/commit/16265a049d1d7b8498bd54b9ba154acfc98bc025
https://github.com/cortexproject/cortex/commit/9ba848b46c8f0b60302d422bdebf9c5e22f9f301
https://github.com/cortexproject/cortex/commit/ff0d52e6d2a3b1be11c4111604fe5f79c892c967
https://github.com/cortexproject/cortex/commit/a2be3d834ee380fc9364d905e1461dc407b5d6e8
and generally 
https://github.com/cortexproject/cortex/blob/master/CHANGELOG.md#master--unreleased

Cortex bump and dashboard enhancement

---

packages/controller/src/resources/loki/index.ts

 use Recreate strategy for Loki compactor so it can transfer PV

---

packages/controller-config/src/docker-images.json

https://github.com/grafana/loki/compare/03aaa34...cb59069

loki: bump to latest master

---

packages/controller/src/resources/monitoring/system/dashboards/loki-overview-per-tenant.json

Some of the panels in this dashboard were broken as of infra and architecture changes. This fixes them. Saved with the browser.
That's how things looked right before saving:

dashboards: fix loki overview panels

---

packages/controller/src/resources/monitoring/system/dashboards/cortex-overview-per-tenant.json

cortex api proxy read direction panels: this fixes/consolidates the query and adjusts the title

dashboards: cortex overview: fix/improve query panels

---

go/pkg/authenticator/keyset.go
go/pkg/authenticator/keyset_test.go
packages/cli/src/index.ts

This addresses https://github.com/opstrace/opstrace/issues/450.

API proxy authenticator: relax key set config validation, wip

---

test/test-remote/logstream-gen/index.ts

https://github.com/opstrace/opstrace/issues/447

looker: strip whitespace from token file contents

---

lib/dns/src/opstrace.ts

cli: dns client: plan for 404 upon DELETE

---

go/cmd/cortex/main.go
go/pkg/authenticator/authenticator.go
go/pkg/authenticator/http.go
go/pkg/authenticator/jwt.go
go/pkg/middleware/proxy.go
go/pkg/middleware/proxy_test.go

Context: https://github.com/opstrace/opstrace/issues/464

Cortex proxy 429 rewrite / authenticator changes

---

packages/app/src/state/tenant/hooks/useTenantList.ts
packages/app/src/state/tenant/reducer.ts
packages/app/src/state/tenant/types.ts

rather than array for better merging. like I recently did for users.
Signed-off-by: Nahum Wild <nahum@opstrace.com>

ui: switched tenant reduct storage to being object/record based

---

packages/controller-config/src/docker-images.json

https://github.com/grafana/loki/compare/faa1ea...v2.2.0
https://github.com/grafana/loki/commit/8012362674568379a3871ff8c4a2bfd1ddba7ad1

bump: loki 2.2.0

---

packages/app/docker-compose.yml
packages/controller-config/src/docker-images.json

chore: Bump config image tag to latest

---

packages/controller/src/resources/monitoring/system/dashboards/cortex-overview-per-tenant.json

dashboards: cortex overview: tweak, new panels

---

lib/kubernetes/src/crds/kube-prometheus/alertmanager.ts
lib/kubernetes/src/crds/kube-prometheus/podmonitor.ts
lib/kubernetes/src/crds/kube-prometheus/probe.ts
lib/kubernetes/src/crds/kube-prometheus/prometheus.ts
lib/kubernetes/src/crds/kube-prometheus/prometheusrule.ts
lib/kubernetes/src/crds/kube-prometheus/servicemonitor.ts
lib/kubernetes/src/crds/kube-prometheus/thanosruler.ts

Replace 2-liner with 1-liner (ht @terrcin for pointing out the better syntax)

chore: Simplify/clean up imports in CRD wrappers

---

.github/workflows/process-images.yml
.github/workflows/upload-assets.yml

Scope the image processing and upload actions to `/docs/assets`
Signed-off-by: Patrick Heneise <patrick@zentered.co>

chore: scope upload and image action to docs/assets

---

.gitignore
packages/app/.env.client.development
packages/app/.eslintrc.js
packages/app/src/client/utils/rendering.tsx
packages/app/src/client/views/cluster/AlertmanagerConfigEditor.tsx
packages/app/src/state/clients/graphqlClient/index.ts
packages/app/src/state/clients/graphqlClient/subscriptionClient.ts
packages/app/src/state/form/actions.ts
packages/app/src/state/form/hooks/index.ts
packages/app/src/state/form/hooks/useForm.ts
packages/app/src/state/form/reducer.ts
packages/app/src/state/form/types.ts
packages/app/src/state/form/utils.ts
packages/app/src/state/reducer.ts
packages/app/src/state/tenant/actions.ts
packages/app/src/state/tenant/hooks/useTenantList.ts
packages/app/src/state/tenant/sagas/index.ts
packages/app/src/state/utils/__tests__/getSubscriptionID.test.ts
yarn.lock

If server side validation fails when publishing Alertmanager config changes update UI to reflect this and pass through the error message

ui: alertmanager cortex validation

---

lib/aws/src/util.ts

- fix: build upper bond. See #511.
- use same strategy for all err cases
- improve code comments
- add: a little jitter
- bump connect() timeout a tiny bit (explain
trade-off)

chore: aws/util.ts: retrying: consolidate

---

docs/guides/user/collecting-cloud-metrics.md

First draft, likely needs restructuring to be a proper guide. Anything that sticks out as missing?

docs: add cloud metrics/exporters guide (fixes #358)

---

go/pkg/config/credential.go
go/pkg/config/exporter.go
go/pkg/graphql/client_generated.go
packages/app/package.json
yarn.lock

Pick up fix from https://github.com/ctison/graphql-codegen-golang/pull/1

config: Bump go graphql generator, remove workaround to mislabeled fields

---

docs/manifest.json

docs: Add cloud metrics user guide to menu

---

go/cmd/config/README.md
go/cmd/config/config_types.go
go/cmd/config/credential_api.go
go/cmd/config/exporter_api.go
go/cmd/config/hasura_handler.go
go/cmd/config/main.go
go/pkg/graphql/access.go
packages/app/docker-compose.yml
packages/controller-config/src/docker-images.json

Fix issues around JSON (via hasura) vs YAML (via HTTP API) input. Had put this down for a bit until it was needed - and it sounds like it's now needed.

config: Fix credential validation via hasura actions

---

README.md

Proposing a couple of immediate changes to the readme, removing extraneous text.

docs(readme): streamline by removing unnecessary content

---

README.md
ci/cluster-config.yaml
docs/quickstart.md
packages/cli/src/schemas.ts

chore: update default config values to make config more friendly

---

packages/app/src/client/views/login/index.tsx

Signed-off-by: Mat Appelman <mat@opstrace.com>

chore: add cluster name to auth0 login context

---

ci/test-upgrade/upgrade-cluster.sh

Fix missing flag in upgrade command.

ci: upgrades - add path to cluster config

---

packages/controller/src/reducers/graphql/credentials.ts
packages/controller/src/reducers/graphql/exporters.ts

I thought this was working fine before, maybe I just didn't notice that the last one wasn't being deleted in practice.

controller: Fix deletion of the last credential or exporter (empty array case)

---

packages/controller-config/src/docker-images.json

Test latest off master for cortexproject/cortex#3817.  /cc @sreis

bump: cortex to head of master (d302dc4) to pull in fix

---

packages/controller/src/resources/monitoring/system/dashboards/looker.json
test/test-remote/logstream-gen/index.ts

looker: metrics fixes, dashboard fixes, log msgs improvements, code comments

---

README.md

See: https://opstrace.com/blog/introducing-the-open-source-distribution

update the readme intro based on "distribution" blog post

---

packages/controller/src/resources/ingress/certManager.ts

Check https://github.com/opstrace/opstrace/issues/151#issuecomment-822376184 for more details.

fix: disable cert-manage ca-injector leader election

---

ci/cluster-config.yaml
docs/guides/contributor/workflows.md
docs/references/cluster-configuration.md

@jgehrcke rightly identified that I forgot to update all of the documentation in #545.  Fixing `cluster-configuration.md` here.  
Since I'm in the documentation, I make some additional changes for grammar and content.

clean up after #544/#545, make some additional edits along the way

---

packages/upgrader/src/index.ts

Previously it was waiting for the full upgrade to finish. Now it retries the infrastructure upgrade (same as create and destroy command) then it proceeds to upgrade the controller and wait for it to rollout the Kubernetes resources upgrade.
Already ran the upgrade test from this branch and came [back green](https://buildkite.com/opstrace/upgrade-tests/builds/441#0453688f-c450-48d9-a205-54c342fb65b8).
Close #563

cli: split upgrade wait loop by infra and controller

---

packages/app/src/client/viewsBasic/cloudMetrics/tabs/Exporters/Table.tsx

and updated to be tenant sensitive
Signed-off-by: Nahum Wild <nahum@opstrace.com>

ui: tweak logql query for finding cloudwatch exceptions

---

ci/test-cli/cli-tests-with-cluster.sh
lib/aws/src/eks.ts
lib/gcp/src/cluster.ts
packages/cli/src/aks.ts
packages/cli/src/createTenantAuthToken.ts
packages/cli/src/crypto.ts
packages/cli/src/destroy.ts
packages/cli/src/index.ts
packages/cli/src/list.ts
packages/cli/src/upgrade.ts
packages/cli/src/util.ts
packages/controller-config/src/aks.ts
packages/controller-config/src/index.ts
packages/controller-config/src/schema.ts
packages/controller-config/src/schemav1.ts
packages/controller-config/src/tasks/api.ts
packages/installer/src/readiness.ts

idea:
- look up running cluster
- generate kube config object
- mutate authenticator config map

CLI: add complete flow for custom key pair management for tenant authentication

---

packages/cli/src/list.ts
packages/cli/src/util.ts

This is to address https://github.com/opstrace/opstrace/issues/581.

CLI: destroy/upgrade/... AWS region lookup: detect when retries exceeded, handle

---

test/test-remote/testutils/logs.ts

In the context of a poll loop, we can set the timeout to be fairly short so that we can try again quickly in the event of a spurious request timeout.

test-remote: Adjust loki query options for handling spurious timeouts (#611)

---

docs/guides/user/collecting-cloud-metrics.md

Just some quick tweaks adding context to the images.

docs: Improve image placement in cloud metrics guide

---

docs/README.md
docs/guides/user/collecting-cloud-metrics.md
docs/guides/user/sending-logs-with-fluentd.md
docs/guides/user/sending-logs-with-promtail.md

docs: fix broken links

---

.github/workflows/process-images.yml

Signed-off-by: Gábor Lipták gliptak@gmail.com

Bump Tinify GHA to 1.3.1

---

docs/guides/contributor/setting-up-your-dev-env.md

Signed-off-by: Mo Sattler <hi@mosattler.com>

docs(contributor-guide): fix typo

---

packages/app/src/client/views/sidebar/TenantPanel.tsx
packages/app/src/client/views/sidebar/index.tsx
yarn.lock

This reverts https://github.com/opstrace/opstrace/pull/399. Together with a guide for how to create tenant-specific authentication tokens this will be a core piece of the initial "how to add a new tenant" story.

ui: re-enable 'create tenant'

---

test/test-remote/test_exporters.ts

test-remote: List credentials/exporters after POSTing one (debugging #615)

---

packages/app/src/client/hooks/useGrafana.ts
packages/app/src/client/viewsBasic/cloudMetrics/tabs/Exporters/Table.tsx
packages/app/src/client/viewsBasic/common/dateTime.ts
packages/app/src/client/viewsBasic/integrationDefs/k8sMetrics/CheckStatusBtn.tsx
packages/app/src/client/viewsBasic/integrationDefs/k8sMetrics/Show.tsx

It directly checks with grafana if it's received metrics from the installed integration yet.

ui: added a "check status" button to show page of integration

---

packages/cli/src/list.ts

For https://github.com/opstrace/opstrace/issues/734.

cli: try to fix #734

---

.gitignore
packages/app/Makefile
packages/app/README.md
packages/app/config/webpack.server.config.js
packages/app/package.json

Upgrade Telepresence to v2 for remote ui dev.

Remote UI Dev: upgrade telepresence for the ubuntu peeps

---

packages/app/src/client/viewsBasic/integrationDefs/k8sMetrics/Show.tsx
packages/app/src/client/viewsBasic/integrationDefs/k8sMetrics/templates/config.ts

Fixes a couple flagrant issues found when testing off of `main`.

ui: Quick fixes for metrics configs (#741)

---

packages/app/src/client/viewsBasic/integrationDefs/k8sMetrics/Show.tsx
packages/app/src/client/viewsBasic/integrationDefs/k8sMetrics/dashboards/apiserver.js
packages/app/src/client/viewsBasic/integrationDefs/k8sMetrics/dashboards/index.ts
packages/app/src/client/viewsBasic/integrationDefs/k8sMetrics/dashboards/kubelet.js
packages/app/src/client/viewsBasic/integrationDefs/k8sMetrics/templates/commands.ts
packages/app/src/client/viewsBasic/integrationDefs/k8sMetrics/templates/config.ts

ui: Cherrypicked tweaks to metrics relabeling and dashboards from #729

---

packages/app/package.json
packages/app/src/server/routes/api/cortexRuntimeConfig.ts
packages/app/src/server/routes/api/index.ts
packages/app/src/server/server.ts

[WIP] app: add route for setting cortex runtime config (via k8s config map)

---

packages/app/src/client/viewsBasic/integrationDefs/common/ViewConfigButtonModal.tsx
packages/app/src/client/viewsBasic/integrationDefs/common/grafana.ts
packages/app/src/client/viewsBasic/integrationDefs/k8sLogs/Show.tsx
packages/app/src/client/viewsBasic/integrationDefs/k8sMetrics/Show.tsx

ui: include Tenant.name in the K8s-Metrcis/Logs yaml download filename

---

packages/controller/src/resources/cortex/index.ts
packages/controller/src/resources/monitoring/system/dashboards/tenant-overview-cortex.json

Add tenant-overview-cortex.json, enable active series tracking for Cortex

---

packages/controller/src/resources/monitoring/system/dashboards/tenant-overview-cortex.json

Current state from cluster which Ieft running for a couple of days:

dashboards: fix and polish tenant overview for cortex

---

packages/controller/src/resources/monitoring/system/dashboards/tenant-overview-loki.json

dashboards: tenant overview for loki: add initial version

---

packages/cli/src/index.ts
packages/cli/src/upgrade.ts
packages/installer/src/index.ts
packages/upgrader/src/upgrade.ts

Tested locally.
Going to follow up with CI pipeline and docs updates.

upgrade: add support for GCP

---

.buildkite/test-upgrade-pipeline.yml
Makefile
ci/test-upgrade/create-cluster.sh
ci/test-upgrade/preamble.sh
ci/test-upgrade/run.sh
ci/test-upgrade/teardown.sh
ci/test-upgrade/upgrade-cluster.sh

Close #367 
Ran [build separately](https://buildkite.com/opstrace/upgrade-tests/builds/674#4fbd424e-5729-4c45-ae7f-fe194c814050) and it came back green.

ci: run upgrade tests on GCP

---

packages/controller/src/resources/monitoring/system/dashboards/tenant-overview-cortex.json
packages/controller/src/resources/monitoring/system/dashboards/tenant-overview-loki.json

See https://github.com/opstrace/opstrace/pull/777#issuecomment-848767275

dashboards: TO cortex/loki: adjust default timewindow

---

packages/app/src/client/integrations/common/UninstallIntegrationBtn.tsx
packages/app/src/client/integrations/k8sLogs/Show/UninstallInstructions.tsx
packages/app/src/client/integrations/k8sMetrics/Show/UninstallInstructions.tsx

ui: for integrations renamed "delete" copy to "uninstall"

---

packages/app/src/client/components/Button/Button.tsx

Removed a not necessary intermediate component `BaseButton`.

refactor(Button): minor cleanup

---

packages/app/src/client/components/NotificationsList/NotificationItem.tsx
packages/app/src/client/components/NotificationsList/NotificationsListHeader.tsx

Slightly improved border radius and colours. 
I didn't mess to much with the colors as those are the standard MUI colors. If we want to deviate from that, let me know!

feat(NotificationService): improve styles

---

packages/controller/src/resources/monitoring/system/dashboards/tenant-overview-cortex.json

Not particularly beautiful, but useful.

dashboards: TO cortex: add panel with active metrics count

---

lib/aws/src/policy.ts

fix: handle paginated results in aws iam list policy

---

packages/app/src/server/env.ts
packages/app/src/server/envParser.test.ts
packages/app/src/server/envParsers.ts

Small suggestion on cleaning up a little bit the env file.

feat(server): refactor env

---

packages/app/src/client/views/ring-health/index.tsx
packages/app/src/server/routes/api/cortex/cortex.test.ts
packages/app/src/server/routes/api/cortex/index.ts

feat(ring-health): add alert manager

---

packages/app/package.json
packages/app/src/client/views/ring-health/RingHealth.test.tsx
packages/app/src/client/views/ring-health/RingTable.tsx
packages/app/src/client/views/ring-health/TokenDialog.tsx
yarn.lock

feat(ring-health): make forgettable

---

packages/app/src/client/app.tsx
packages/app/src/client/views/ring-health/cortex/RingHealth.test.tsx
packages/app/src/client/views/ring-health/cortex/index.tsx
packages/app/src/client/views/ring-health/loki/RingHealth.test.tsx
packages/app/src/client/views/ring-health/loki/index.tsx
packages/app/src/server/routes/api/index.ts
packages/app/src/server/routes/api/loki/index.ts

Extending the work done for Cortex here: https://github.com/opstrace/opstrace/pull/816

Add Loki Ring state and forget buttons to UI

---

go/cmd/config/README.md
packages/app/src/client/integrations/common/ExporterStatus.tsx
packages/app/src/client/integrations/exporterAzure/Form.tsx
packages/app/src/client/integrations/exporterAzure/Show/Details.tsx
packages/app/src/client/integrations/exporterAzure/Show/index.tsx
packages/app/src/client/integrations/exporterAzure/Status.tsx
packages/app/src/client/integrations/exporterAzure/index.tsx
packages/app/src/client/integrations/exporterBlackbox/Status.tsx
packages/app/src/client/integrations/exporterBlackbox/index.tsx
packages/app/src/client/integrations/exporterCloudMonitoring/Form.tsx
packages/app/src/client/integrations/exporterCloudMonitoring/Show/index.tsx
packages/app/src/client/integrations/exporterCloudMonitoring/Status.tsx
packages/app/src/client/integrations/exporterCloudMonitoring/index.tsx
packages/app/src/client/integrations/exporterCloudWatch/Form.tsx
packages/app/src/client/integrations/exporterCloudWatch/Show/index.tsx
packages/app/src/client/integrations/exporterCloudWatch/Status.tsx
packages/app/src/client/integrations/exporterCloudWatch/index.tsx
packages/controller/src/resources/integrations/index.ts

TODO: verify that the status checks still work - tweak as needed, For this I need to book time with @nickbp for testing this with AWS, GCP, and Azure as he's done this before and it'd be waaaay faster than me fumbling about.

ui: remove EARLY_PREVIEW flag from Export Integrations 

---

packages/app/src/client/integrations/exporterAzure/index.tsx

ui: tweaked description for Azure exporter integration

---

packages/app/src/client/views/ring-health/RingHealth.tsx
packages/app/src/client/views/ring-health/cortex/RingHealth.test.tsx
packages/app/src/client/views/ring-health/cortex/index.tsx
packages/app/src/client/views/ring-health/loki/RingHealth.test.tsx
packages/app/src/client/views/ring-health/loki/index.tsx

chore(app): deduplicate code between cortex and loki ring health

---

docs/references/cli.md
docs/references/concepts.md

docs: update more content

---

lib/aws/src/bucket.ts

Attempt to fix https://github.com/opstrace/opstrace/issues/841.

chore: lib/aws: fix s3 bucket create for us-east-1

---

lib/aws/src/iamRole.ts

fix: handle paginated results in aws iam list roles

---

docs/guides/administrator/gcp-setup.md

Adds information regarding quotas.

Adds GCP quota info

---

README.md

Now that we have releases, we could highlight that the top of the readme with a calver badge:

chore: refresh and other nits for the README

---

test/test-remote/nodejs-testrunner.Dockerfile

See [this](https://opstrace-community.slack.com/archives/C01KZS8JRNC/p1622821569060600?thread_ts=1622818862.054700&cid=C01KZS8JRNC) and following messages.

fix(test-remote): dockerfile for mac

---

packages/app/src/client/integrations/exporterAzure/Form.tsx
packages/app/src/client/integrations/exporterCloudMonitoring/Form.tsx
packages/app/src/client/integrations/exporterCloudWatch/Form.tsx

ui: don't auto-create empty grafana folder for exporter integrations

---

README.md

I went through the readme and noticed a couple of small things; proposed changes on the fly.

README: minor polish proposal

---

packages/app/src/client/views/ring-health/RingTable.tsx

ui(ring-health): handle more errors

---

packages/controller/src/resources/monitoring/tenants/grafanaDatasources.ts

Fix #896.
Using a variable in proxy_pass forces re-resolution of the DNS names because NGINX treats variables differently to static configuration. For this, to work we need to also set a resolver but EKS and GKE use different ClusterIPs for the pod DNS upstream resolver so we have to account for that.

fix: handle service restarts in grafana datasource splitter

---

packages/controller/src/tasks/syncTenants.ts

Following up on comments left by @jgehrcke:
https://github.com/opstrace/opstrace/pull/870#discussion_r651805486
https://github.com/opstrace/opstrace/pull/870#discussion_r651795390

improve the setting of default Alertmanager config for tenants during tenant sync

---

packages/controller-config/src/resources/controller.ts
packages/controller/src/tasks/cortexRules.ts
packages/controller/src/tasks/syncTenants.ts

controller: Env-configurable alertmanager/ruler endpoints, use 'main' not master for repo runbook path

---

test/browser/README.md

No code changes, just new documentation, so merging without a CI run

ui: added README.md to test/browser to explain auth and aid contributors

---

packages/upgrader/src/index.ts

This is a workaround for opstrace/opstrace#905 to force the loki querier to set up the credentials to access the S3 storage bucket.
Close #905.

cli: on upgrade check api endpoints are reachable

---

packages/app/config/jest/setupTests.js
packages/app/src/client/views/ring-health/cortex/RingHealth.test.tsx
packages/app/src/client/views/ring-health/loki/RingHealth.test.tsx

ui(ring-health): fix flaky unit tests

---

test/test-remote/test_ui.ts

to help better understand https://github.com/opstrace/opstrace/issues/917

test-remote: test_ui_api: screenshot when login fails

---

packages/controller-config/src/docker-images.json

https://github.com/grafana/loki/compare/v2.2.1...81e100f
interesting commits:
* https://github.com/grafana/loki/commit/806d6a503e1746a158f332d055f5d9fbd8b28d1a
* https://github.com/grafana/loki/commit/59bb6d3fbab553f72f8f16ed9e6769730bbe561a
* https://github.com/grafana/loki/commit/d362df7a98a4ba409a10a5e24b869fb8c41cdbc8
* https://github.com/grafana/loki/commit/2b7a6f201cd5065c1b4b9fea8b16197af2d2bc33
* https://github.com/grafana/loki/commit/ae23b7e4ed54f4e5b932f5ff814f7dab0f2d5db5
* https://github.com/grafana/loki/commit/9137ef921bf97acdf1beb7e15506dd5a2bbc4331
* https://github.com/grafana/loki/commit/8694e7303a301a21c8e495e8c43b902dee7a3a96

bump: loki main-81e100f

---

ci/test-upgrade/create-cluster.sh

ci(upgrades): update create command parameter

---

packages/uninstaller/src/aws.ts

cli: destroy: fix s3 bucket teardown

---

packages/app/src/client/views/common/SideBar.tsx
packages/app/src/client/views/integrations/all/All.tsx
test/browser/fixtures/authenticated.ts
test/browser/package.json
test/browser/playwright.config.ts
test/browser/tests/authentication.spec.ts
test/browser/tests/everywhere.spec.ts

Have the CI browser go everywhere in the app in the single test - rather than regular tests that often just test a small part of a particullar page.

[wip] ui: ci go "everywhere" in the one test, test

---

test/browser/tests/everywhere.spec.ts

this tripples it's allowable time

ui: mark the everywhere browser test as "slow"

---

packages/app/src/state/tenant/hooks/useTenant.test.tsx
packages/app/src/state/tenant/hooks/useTenant.ts

ui: add hook to retrieve last selected tenant

---

packages/app/src/client/views/tenants/TenantPicker.tsx
packages/app/src/state/tenant/hooks/useTenant.test.tsx
packages/app/src/state/tenant/hooks/useTenant.ts

ui: preserve route when switching tenants

---

packages/app/src/client/app.tsx
packages/app/src/state/tenant/hooks/useTenant.test.tsx
packages/app/src/state/tenant/hooks/useTenant.ts

ui: prevent forgetting selected tenant when navigating to admin cluster

---

packages/controller/src/resources/loki/index.ts

A workaround to ensure the queriers are initialized properly.
From https://github.com/grafana/loki/issues/3085. The queriers initialize the storage credentials in the query evaluation code path. To ensure the querier is initialized before being marked ready to receive requests we query the labels endpoint in the system tenant until we get a 200 OK. The system tenant is created by default. This means the queriers startupProbe waits for the ingesters to receive some data.
The startupProbe indicates whether the application within the container is started. All other probes are disabled if a startup probe is provided, until it succeeds. The readinessProbe indicates whether the container is ready to respond to requests. If the readiness probe fails, the endpoints controller removes the Pod's IP …

loki: define querier startup probe

---

ci/create-cluster-artifacts.sh

ci: fix unbound docker logs collection

---

packages/controller/src/resources/cortex/index.ts

By default, the ingester and distributor have an unlimited queue for pending push requests. This can lead to OOMing pods under heavy load (ingesters: lots of new series, distributors: large payloads with lots of labels).
This is a particular issue with ingesters, which lose in-memory state and take a while to recover, during which time cortex as a whole can become degraded.
These limits should reduce the likelihood of OOMing regardless of load. The comments give some justification around the chosen values, for more background see #966.

controller: Configure inflight push request limits

---

packages/cli/src/schemasv2.test.ts
packages/config/src/clusterconfig.ts

Addresses [this](https://github.com/opstrace/opstrace/issues/710#issuecomment-871300624).

cli: cluster config: tenant name may not contain hyphen

---

packages/app/src/client/utils/regex.ts
packages/app/src/client/validation/alertmanager/config/common.ts
packages/app/src/client/views/tenants/AddTenantDialog.tsx
packages/app/src/client/views/tenants/DeleteTenantDialog.tsx
packages/app/src/client/views/tenants/deleteTenant.tsx
test/browser/fixtures/authenticated.ts
test/browser/fixtures/index.ts
test/browser/fixtures/tenant.ts
test/browser/package.json
test/browser/tests/authentication.spec.ts
test/browser/tests/everywhere.spec.ts
test/browser/tests/tenant.spec.ts
test/browser/utils/tenant.ts

testing to make sure user can't create tenant that have invalid chars in their names: `-`, `_`, `:`, ` `, `.`

ui: browser tests - tenant name validation

---

ci/test-upgrade/create-cluster-artifacts.sh
ci/test-upgrade/run.sh

ci(test-upgrades): collect cluster artifacts

---

Makefile
test/browser/tests/debugging.spec.ts

Getting lots of timeout intermittent failures for browser tests. Enabling debugging to get more information.

ui: set playwright debugging env var

---

test/test-remote/looker/src/args.ts
test/test-remote/looker/src/index.ts
test/test-remote/looker/src/logs/dummystream.ts
test/test-remote/looker/src/metrics/dummyseries.ts
test/test-remote/looker/src/series.ts
test/test-remote/test_loki_log_ingest_api.ts
test/test-remote/test_prom_remote_write.ts

Various cleanup following #995, shouldn't change actual functionality

looker: Misc follow-up fixes to log messages, comments, and variable names

---

Makefile
containers/ci/opstrace-ci.Dockerfile
containers/controller/Dockerfile
docs/guides/contributor/setting-up-your-dev-env.md
package.json
packages/app/Dockerfile.app
packages/cli/src/ucc.spec.ts
packages/controller/src/reducers/graphql/integrations.ts
packages/uninstaller/src/index.ts
test/test-remote/looker/README.md
test/test-remote/nodejs-testrunner.Dockerfile
yarn.lock

CLI: move to NodeJS 16.x

---

ci/test-upgrade/create-cluster-artifacts.sh
ci/test-upgrade/run.sh

ci(upgrades): collect looker artifacts

---

packages/upgrader/src/upgrade.ts

#861 Introduced a new field in the user instance config file and CI requires it to be set to run the login flow for the UI tests. 
The code path that handles the controller configuration upgrade does not take into account updates to the user cluster config (ex. add new tenants via the config file). For now, just pass the custom_auth0_client_id. Other fields (ex. number of nodes in the instance) need to be handled on a case by case basis to ensure safe(ish) upgrades.

fix: set custom_auth0_client_id in controller config

---

test/browser/package.json

no code changes, just straight merging without waiting on CI

ui: updated env vars for running tests locally

---

packages/controller/src/resources/cortex/index.ts

Also remove unnecessary cases that already align with what `roundDownToOdd(Nnodes)` calculates.
(Fixes #1045)

cortex: fix ingester replicas cliff at 21 nodes

---

packages/app/src/server/routes/api/cortex/cortex.test.ts
packages/app/src/server/routes/api/cortex/index.ts

Improve error handling of ring-health errors, as outlined [here](https://github.com/opstrace/opstrace/pull/900#issuecomment-868528836).

ui(ring-health): improve error handling

---

packages/app/src/server/routes/api/cortex/cortexRuntimeConfig.ts

chore: fix tsc compile error due to missing param

---

Makefile
ci/deploy-testremote-teardown.sh
ci/test-core.sh
ci/test-upgrade/run.sh

For addressing https://github.com/opstrace/opstrace/issues/1051.

ci: deduplicate code into test-core.sh

---

packages/app/src/client/views/users/list.tsx
test/browser/tests/authentication.spec.ts
test/browser/tests/everywhere.spec.ts
test/browser/tests/regression.spec.ts

Making sure issue #1000 doesn't happen again

ui: issue 1000 regression tests

---

packages/controller-config/src/docker-images.json

https://github.com/grafana/loki/compare/81e100f...1ed19f7380fb2248d2794b01a7091b3c5774f9c6
https://github.com/grafana/grafana/compare/v8.0.3...v8.0.6
https://github.com/grafana/grafana/releases/tag/v8.0.6
https://github.com/grafana/grafana/releases/tag/v8.0.5
https://github.com/grafana/grafana/releases/tag/v8.0.4

Bump Grafana and Loki

---

packages/app/config/jest/setupTests.js
packages/app/src/client/utils/grafana.test.ts

While working on general error handling I was working in the wrong place for a bit, and only realised later. 
The only useful part that came out of it is these tests, so I thought I open a PR for it.

ui(grafana): add test for folder deletion

---

packages/controller/src/tasks/readiness.ts

Should be useful for tracking down when something is stuck, or slowing down installation
(May help with tracking CI slowness during install)

controller: when <=5 items are pending, log their names/statuses

---

Makefile

standalon PR not based on https://github.com/opstrace/opstrace/pull/1076

ui: switch back to logging in once per worker

---

test/test-remote/test_alerts.ts

- Set up E2E loop in default and system tenants in parallel
- Skip reporting-but-zero-alerts check since it's a bit redundant, and instead set up alertmanager config at the start

test-remote: speed improvements for alerts E2E tests

---

test/test-remote/test_ui_api.ts

See commit message.
This is supposed to diminish / obliterate the impact of
https://github.com/opstrace/opstrace/issues/340
https://github.com/opstrace/opstrace/issues/789
https://github.com/opstrace/opstrace/issues/917
https://github.com/opstrace/opstrace/issues/990
https://github.com/opstrace/opstrace/issues/1003
Some of these tickets mix instability symptoms in `test-browser` and `test-remote`. When that is the case, then this patch is supposed to address those instabilities that lead to errors in `test_ui_api`.

test-remote: test_ui_api: retry browser-based login

---

packages/app/src/client/views/getting-started/index.tsx

Responding this this suggestion: https://opstrace.slack.com/archives/C0271MTMS23/p1626789514012500

ui: added metrics and logs endpoint urls to tenant Getting Started page

---

packages/app/src/client/components/withSession/pages/AccessDenied.tsx

Signed-off-by: Mo Sattler <hi@mosattler.com>

ui: fix missing CondRender

---

packages/app/package.json
packages/app/src/client/components/Editor/lib/types.ts
packages/app/src/client/components/Form/ControlledInput.tsx
packages/app/src/client/components/List/List.tsx
packages/app/src/client/components/List/index.stories.tsx
packages/app/src/client/components/Scrollable/index.stories.tsx
packages/app/src/client/hooks/useHasuraSubscription.ts
packages/app/src/client/integrations/common/UninstallIntegrationBtn.tsx
packages/app/src/client/integrations/exporterAzure/Form.tsx
packages/app/src/client/integrations/exporterCloudMonitoring/Form.tsx
packages/app/src/client/integrations/exporterCloudWatch/Form.tsx
packages/app/src/client/integrations/k8sLogs/Form.tsx
packages/app/src/client/integrations/k8sMetrics/Form.tsx

Improving some of the types (mainly removing `any` and `Function`) and adding a test for `CondRender`, helping me to understand the component better.

ui: improve types

---

packages/app/package.json
packages/app/src/client/integrations/common/UninstallIntegrationBtn.test.tsx
packages/app/src/client/integrations/common/UninstallIntegrationBtn.tsx

Adding user feedback for the uninstallation button for integrations, in case there are server or network problems.

ui(uninstall-integration-button): add error handling

---

packages/app/src/client/components/withSession/index.tsx

Handling unhandled exception caught by Sentry:
https://sentry.io/organizations/opstrace/issues/2535024087/?environment=production&project=5529515&query=is%3Aunresolved

ui: beefed up error handling when trying to create Opstrace Session

---

packages/app/src/client/integrations/common/UninstallIntegrationBtn.test.tsx
packages/app/src/client/integrations/k8sMetrics/Show/InstallInstructions.test.tsx
packages/app/src/client/integrations/k8sMetrics/Show/InstallInstructions.tsx
packages/app/src/client/integrations/k8sMetrics/Show/dashboards/index.ts

Error handling of the "Install Dashboard" button

ui(InstallInstructions): add error handling

---

packages/controller/src/resources/apis/loki.ts
packages/controller/src/resources/loki/index.ts
packages/controller/src/resources/monitoring/tenants/grafanaDatasources.ts
test/test-remote/test_loki_log_ingest_api.ts

* Applies some config options from [loki production settings](https://github.com/grafana/loki/blob/main/production/ksonnet/loki/config.libsonnet).
Close https://github.com/opstrace/private/issues/35.

chore: add loki query-frontend

---

packages/app/src/client/integrations/exporterAzure/Form.tsx
packages/app/src/client/integrations/exporterCloudMonitoring/Form.tsx
packages/app/src/client/integrations/exporterCloudWatch/Form.tsx
packages/app/src/client/integrations/k8sLogs/Form.tsx
packages/app/src/client/integrations/k8sMetrics/Form.tsx

Deduplication by depriving types from yup schema instead of typing it manually.

ui: deduplication of schema validation

---

packages/app/package.json
packages/app/src/client/app.tsx
packages/app/src/client/components/withSession/pages/AccessDenied.tsx
packages/app/src/client/components/withSession/pages/Login.tsx
packages/app/src/client/index.tsx
packages/app/src/client/services/index.tsx
packages/app/src/client/views/login/index.tsx
packages/app/src/client/views/users/detail.tsx
packages/app/src/state/clients/graphqlClient/initSubscriptions.tsx
packages/app/src/state/clients/graphqlClient/subscriptionClient.ts
packages/app/src/state/clients/graphqlClient/withSubscriptions.tsx
packages/app/src/state/cortex-config/sagas/index.ts
packages/app/src/state/integration/sagas/integrationListSubscription.ts
packages/app/src/state/tenant/sagas/tenantListSubscription.ts
packages/app/src/state/user/hooks/__tests__/useCurrentUser.test.tsx
packages/app/src/state/user/hooks/useCurrentUser.ts
packages/app/src/state/user/sagas/userListSubscription.ts
tsconfig.json
yarn.lock

This resolves all the WS setup errors we see in the dev console before you login etc...

ui: setup subscription client after session is verified

---

packages/app/src/client/components/Form/SelectInput.tsx
packages/app/src/client/integrations/k8sLogs/Form.tsx

Signed-off-by: Nahum Wild <nahum@opstrace.com>

ui: removing use of CondRender, was accidently added back in via a long lived PR

---

Makefile

ui: switching back to single worker for browser tests to limit number of login attempts to auth0

---

ci/deploy-testremote-teardown.sh
docs/guides/contributor/setting-up-your-dev-env.md

ci: try to debug / tackle instability 1068

---

packages/cli/src/list.ts

chore: temporarily remove cn-* regions due to ci instability (socket timed out without establishing a connection)

---

yarn.lock

why this needs to be done: https://github.com/browserslist/browserslist#browsers-data-updating

task: followed up on yarn warning about caniuse-lite being out of date

---

test/test-remote/test_alerts.ts
test/test-remote/testutils/deployment.ts

test-remote: Add explicit wait for e2ealerting pod to come up

---

.buildkite/pipeline.yml
lib/gcp/package.json
lib/gcp/src/cloudSQL.ts
packages/cli/package.json
yarn.lock

Context: #293.
Also, bump GCP client libraries.

cli: installer: gcp: follow VPC creation via observing long-running operation, retry on all levels and emit error detail

---

lib/gcp/src/cloudSQL.ts
lib/gcp/src/globalAddress.ts

follow-up after https://github.com/opstrace/opstrace/pull/1197, for #293.

cli: create: gcp: log more detail

---

.prettierignore
ci/preamble.sh
lib/aws/src/autoScalingGroup.ts
lib/aws/src/launchConfiguration.ts
lib/aws/src/route53.ts
lib/aws/src/securityGroup.ts
lib/gcp/src/cluster.ts
lib/gcp/src/iam.ts
lib/kubernetes/src/equality/utils.ts
lib/kubernetes/src/kinds/CustomResourceDefinition.ts
lib/kubernetes/src/kinds/PersistentVolumeClaim.ts
lib/kubernetes/src/readiness/index.ts
lib/utils/src/docker.ts

Towards https://github.com/opstrace/opstrace/issues/1203.

ci: enforce prettier check on TypeScript source files in lib/

---

ci/preamble.sh
containers/ci/opstrace-ci.Dockerfile
test/test-remote/looker/src/args.ts
test/test-remote/looker/src/index.ts
test/test-remote/looker/src/logs/dummystream.ts
test/test-remote/looker/src/logs/index.ts
test/test-remote/looker/src/metrics/dummyseries.ts
test/test-remote/looker/src/prommetrics.ts
test/test-remote/test_alerts.ts
test/test-remote/test_dd.ts
test/test-remote/test_exporters.ts
test/test-remote/test_systemmetrics.ts
test/test-remote/testutils/deployment.ts
test/test-remote/testutils/index.ts
test/test-remote/testutils/portforward.ts

For https://github.com/opstrace/opstrace/issues/1203
Also see commit messages.

ci: run prettier --check 'test/**/*.ts'

---

ci/deploy-testremote-teardown.sh
ci/test-upgrade/run.sh

Small sample result is that #293 is limited to ddd and fff.
Showing the data set soon.

ci: remove gcp projects d+f, add a+b+c

---

packages/app/src/client/integrations/exporterAzure/Form.tsx
packages/app/src/client/integrations/exporterAzure/Status.tsx
packages/app/src/client/integrations/exporterCloudMonitoring/Form.tsx
packages/app/src/client/integrations/exporterCloudMonitoring/Status.tsx
packages/app/src/client/integrations/exporterCloudWatch/Form.tsx
packages/app/src/client/integrations/exporterCloudWatch/Status.tsx
packages/app/src/client/integrations/k8sLogs/Form.tsx
packages/app/src/client/integrations/k8sLogs/Status.tsx
packages/app/src/client/integrations/k8sMetrics/Form.tsx
packages/app/src/client/integrations/k8sMetrics/Status.tsx
packages/app/src/client/integrations/types.ts
packages/app/src/client/views/integrations/all/Show.tsx

Right now, the props of the integration components are not type checked. This PR changes that. More info in the code annotations.
This PR is a subset of #1199

ui(integration): fix typing

---

packages/app/src/state/graphql-api-types.ts

Using the official gql types instead of manually made ones.

ui: deduplicate gql types

---

packages/app/src/client/integrations/types.ts
packages/app/src/client/utils/grafana.ts
packages/app/src/client/views/integrations/all/All.tsx
packages/app/src/client/views/integrations/all/Install.tsx
packages/app/src/state/clients/graphqlClient/index.ts

Handling request errors for installing integrations.
This PR is a superset of #1200

ui(integrations): handle install error

---

packages/app/src/client/utils/request.ts
packages/app/src/client/views/ring-health/RingHealth.test.tsx
packages/app/src/client/views/ring-health/RingTable.tsx

Adding a preconfigured axios instance to toy with the thought if we can address some of the issues raised by @jgehrcke in #1149 [here](https://github.com/opstrace/opstrace/pull/1149#issuecomment-891062142).
If this is a viable approach to the problem, I can think of some things that still would need to be discussed:
1. What options do we want to preconfigure with what values?
1. Which one of those options should be easily overwritable by a caller?
I am sure there are more considerations to be made.

ui: add preconfigured axios

---

containers/systemlog-fluentd/Dockerfile
packages/config/src/gke.ts
packages/controller-config/src/docker-images.json
packages/controller/src/resources/apis/systemlogs.ts
test/test-remote/testutils/portforward.ts

Bump GKE to 1.19

---

.buildkite/pipeline.yml
.buildkite/test-upgrade-pipeline.yml
Makefile
ci/deploy-testremote-teardown.sh
ci/invoke-looker.sh
ci/test-core.sh
ci/test-upgrade/create-cluster.sh
ci/test-upgrade/run.sh

See
#1108
#1068
#293
Also rename make target `test-remote-ui` to `test-remote-ui-api` -- see commit msg and code comments for further info.

ci: upgrade test: run all test suites (#1108) and fix instability #1068

---

ci/preamble.sh
ci/test-core.sh
ci/test-upgrade/create-cluster.sh
ci/test-upgrade/run.sh
containers/controller/Dockerfile

See commit messages.
I also added controller image build consolidations into this PR and preamble build log improvements.
This should make 'waiting for preamble feedback' (and live-tailing it) faster and more pleasant.

ci: upgrade tests: feed system logs into collection cluster, fix artifact collection

---

packages/controller/src/system/alerts.ts
packages/controller/src/system/rules.ts

We're a bit behind https://github.com/grafana/cortex-jsonnet.

cortex: update alert and rule definitions

---

packages/app/src/client/components/withSession/index.tsx
packages/app/src/client/views/session/AccessDenied.tsx
packages/app/src/client/views/session/LoginFailed.tsx
packages/app/src/client/views/session/index.tsx
packages/app/src/server/routes/api/authentication.ts
packages/app/src/server/routes/api/jwks.ts
packages/app/src/server/server.ts

UI login: show "Access Denied" view only when appropriate, introduce generic login failure view, enhance robustness

---

ci/test-upgrade/initial-cluster-config.yaml
packages/app/src/server/server.ts
packages/controller/src/cmd.ts
packages/controller/src/resources/app/app.ts

For https://github.com/opstrace/opstrace/issues/1273 and also #1274.

ci: fix initial-cluster-config.yaml; misc

---

packages/app/src/client/integrations/common/UninstallIntegrationBtn.tsx
packages/app/src/client/views/integrations/all/Install.tsx
packages/app/src/state/clients/graphqlClient/index.ts

Making the error handling a bit more expressive.

ui(UninstallIntegrationButton): improve error handling

---

packages/app/src/client/views/integrations/all/All.tsx
packages/app/src/client/views/integrations/installed/Installed.test.tsx
packages/app/src/client/views/integrations/installed/Installed.tsx

ui(integrations): adding tests for installed integration page

---

packages/app/src/client/views/integrations/all/All.test.tsx
packages/app/src/client/views/integrations/all/All.tsx

ui(integrations): add tests

---

containers/ci/opstrace-ci.Dockerfile
go/Dockerfile.config
go/Dockerfile.cortex
go/Dockerfile.ddapi
go/Dockerfile.loki

[Golang 1.17 release notes](https://golang.org/doc/go1.17)

bump: golang 1.17.0

---

test/test-remote/looker/package.json

Third-party dependency issue see https://github.com/thenativeweb/boolean/issues/317.
Close #1308

chore: fix yarn build

---

packages/app/config/jest/setupTests.js

The high timeout time was part of some debugging in the CI and I forgot to undo it ...

ui: lower test timeout time

---

ci/scripts/cleanup-gcp-networks.sh

Helper script to clean up stranded GCP networks from CI builds.

ci: add gcp networks clean up script

---

packages/app/src/client/views/users/DeleteUserDialog.test.tsx
packages/app/src/client/views/users/DeleteUserDialog.tsx

ui(deleteuser): add tests

---

Makefile
ci/deploy-testremote-teardown.sh
ci/test-upgrade/run.sh

ci: add new gcp projects to shard ci builds over

---

packages/controller/src/resources/monitoring/system/controllerServiceMonitors.ts
packages/controller/src/resources/monitoring/system/dashboards/controller.json
packages/controller/src/resources/monitoring/system/index.ts
packages/controller/src/resources/monitoring/system/kubeServiceMonitors.ts
packages/controller/src/resources/monitoring/system/kubeStateMetrics.ts
packages/controller/src/resources/monitoring/system/nodeExporter.ts
packages/controller/src/resources/monitoring/system/prometheusAdaptor.ts

Still a bit barebones but gets things set up for more metrics later.

controller: Set up ServiceMonitor and an initial dashboard with current metrics

---

packages/app/src/client/views/users/DeleteUserDialog.test.tsx

ui: unskip tests

---

packages/app/src/client/services/Picker/types.ts
packages/app/src/client/views/users/DeleteUserDialog.tsx
packages/app/src/client/views/users/UserPicker.tsx
packages/app/src/client/views/users/deleteUser.tsx
packages/app/src/client/views/users/useUserConfirmDeletionPicker.tsx

ui(deleteuser): deduplication of picker code

---

ci/invoke-looker.sh
test/test-remote/looker/README.md
test/test-remote/looker/src/args.ts
test/test-remote/looker/src/index.ts
test/test-remote/looker/src/logs/dummystream.ts
test/test-remote/looker/src/metrics/dummyseries.ts

looker:  better CI log output, better defaults, better logging, more validation, README work, and misc

---

packages/app/src/state/user/sagas/index.ts
packages/app/src/state/user/sagas/sagas.test.ts

Showing errors to the user when user deletion requests fails

ui(deleteuser): error handling

---

packages/controller-config/src/docker-images.json

Interesting:
* https://github.com/grafana/loki/commit/8ef3d5fee9653f8e542bd01cfb50cf05005b00e4 (and with that maybe we completely change #1226)
* https://github.com/grafana/loki/commit/29b07d190de2edab4fc03333e3e224d824b5a677
* https://github.com/grafana/loki/commit/11a0d28b611f834c81eee206e26a66b057e443a2 (preparation of docs for out-of-order writes)
* https://github.com/grafana/loki/commit/6f78ffe33cf8f0d6534db5fe8acd663d790e9020
* https://github.com/grafana/loki/commit/20515a2402fe6941353bbeec5efd04c1d56ce841
* https://github.com/grafana/loki/commit/79d53317dd34d32140fd7067fe68ad1c1c0ab26a
* https://github.com/grafana/loki/commit/668622c8130256b7e8ef90ce04e243c2bafe616f
* https://github.com/grafana/loki/commit/757eeacb884fbe01863b3f7e7758a07365ce00ff
* …

bump: loki to a4b8974

---

packages/app/src/client/views/tenants/AddTenantDialog.test.tsx
packages/app/src/state/tenant/sagas/index.ts

ui(AddTenantDialog): add error handling

---

packages/app/src/state/integration/sagas/index.ts

Adding notification in case something goes wrong with grafana state fetching for integrations

feat(integrations): add error handling for grafana state

---

packages/app/config/jest/setupTests.js
packages/app/src/client/views/tenants/DeleteTenantDialog.test.tsx
packages/app/src/client/views/tenants/DeleteTenantDialog.tsx
packages/app/src/state/tenant/sagas/index.ts

Handle error in case tenant deletion goes wrong.

feat(DeleteTenantDialog): handle error

---

packages/app/config/jest/setupTests.js
packages/app/src/client/themes/Provider.test.tsx
packages/app/src/client/themes/Provider.tsx
packages/app/src/state/user/sagas/index.ts

Error handling with regards to persisting dark mode

ui: handle error when persisting dark mode

---

ci/create-cluster-artifacts.sh

ci: fix cert-manager build artifact collection

---

packages/app/src/client/utils/grafana.ts
packages/app/src/client/utils/request.ts

Adding the [custom request function](https://github.com/opstrace/opstrace/blob/11f1de65e6ba279d532d58ae5d74b0ff3a87fb49/packages/app/src/client/utils/request.ts) to two more places, both of which have good test coverage. 
Once they have been proven to work well, we might want to roll it out to further places, wherever it make sense.

ui: use custom request function

---

lib/aws/src/types.ts
lib/dns/src/opstrace.ts
packages/app/src/client/components/NotificationsList/NotificationsList.tsx
packages/app/src/client/components/withSession/index.tsx
packages/app/src/client/hooks/useHasuraSubscription.ts
packages/app/src/client/views/session/Loading.tsx
packages/installer/src/index.ts
test/test-remote/testutils/index.ts

ui: type refactor + prettier

---

packages/app/src/client/views/getting-started/index.tsx

Signed-off-by: ajayk <ajaykemparaj@gmail.com>

ui: "Remove extra opstrace subdomain "

---

packages/app/src/client/views/cluster-config/opstrace.tsx

ui(opstrace-config): improve typing

---

packages/app/src/state/cortex-config/sagas/cortexConfigSubscription.ts
packages/app/src/state/cortex-config/sagas/index.ts

Guarding against improve typing of generic errors.

ui(cortex-config): fix error handling

---

packages/app/config/jest/setupTests.js
packages/app/src/client/integrations/common/DownloadConfigButton.test.tsx
packages/app/src/client/themes/Provider.test.tsx
packages/app/src/client/utils/testutils/testutils.tsx
packages/app/src/client/views/integrations/all/All.test.tsx
packages/app/src/client/views/integrations/all/Install.test.tsx
packages/app/src/client/views/integrations/all/Show.tsx
packages/app/src/client/views/integrations/installed/Installed.test.tsx
packages/app/src/client/views/ring-health/RingHealth.test.tsx
packages/app/src/client/views/ring-health/cortex/CortexRingHealth.test.tsx
packages/app/src/client/views/ring-health/loki/LokiRingHealth.test.tsx
packages/app/src/client/views/tenants/AddTenantDialog.test.tsx
packages/app/src/client/views/tenants/DeleteTenantDialog.test.tsx
packages/app/src/client/views/tenants/DeleteTenantDialog.tsx
packages/app/src/client/views/users/AddUserDialog.test.tsx
packages/app/src/client/views/users/DeleteUserDialog.test.tsx
packages/app/src/client/views/users/detail.tsx
packages/app/src/state/store.ts

Right now, when using the store in tests, the store get's cached. That lead to a few unstable tests. This PR changes that, and provides every test a fresh store.

ui: fix test leakage

---

packages/app/src/client/integrations/common/UninstallIntegrationBtn.test.tsx
packages/app/src/client/themes/Provider.test.tsx

Remove some mocks and improve testing

ui(UninstallIntegrationButton): improve tests

---

packages/app/package.json
yarn.lock

Updating dependencies, including security patches.

chore: update socket.io-client

---

yarn.lock

Updating deps down in optimize-css-assets-webpack-plugin to get security fixes

chore: update optimize-css-assets-webpack-plugin deps

---

packages/app/package.json
yarn.lock

Updating redis to address https://github.com/advisories/GHSA-35q2-47q7-3pc3

chore: update redis npm package

---

yarn.lock

Addresses https://github.com/advisories/GHSA-px4h-xg32-q955

chore: update nested normalize-url deps

---

yarn.lock

Updating nested dep path-parse and addresses https://github.com/advisories/GHSA-hj48-42vr-x3v9

chore: update path-parse

---

yarn.lock

Updating trim-newlines package to address https://github.com/advisories/GHSA-7p7h-4mm5-852v

chore: update trim-newlines

---

yarn.lock

Update underscore to address https://github.com/advisories/GHSA-cf4h-3jhx-xvhq

chore: update underscore package

---

packages/app/src/client/views/ring-health/cortex/CortexRingHealth.test.tsx

ui: deactivating flaky test

---

yarn.lock

Addresses https://github.com/advisories/GHSA-3wcq-x3mq-6r9p

chore: update dns-packet

---

yarn.lock

Addresses https://github.com/advisories/GHSA-43f8-2h32-f4cj

chore: update hosted-git-info

---

yarn.lock

Adresses https://github.com/advisories/GHSA-58f5-hfqc-jgch

chore: update jose

---

packages/app/package.json
yarn.lock

Addresses https://github.com/advisories/GHSA-5q6m-3h65-w53x

chore: update react-dev-utils

---

packages/app/package.json
yarn.lock

Addresses https://github.com/advisories/GHSA-6fc8-4gx4-v693

chore: update ws and @graphql-codegen/cli

---

go/go.mod
go/go.sum

Updating docker which ships with some security fixes: https://github.com/moby/moby/releases/tag/v20.10.9
Signed-off-by: Mo Sattler <hi@mosattler.com>

chore: update github.com/docker/docker

---

go/go.mod
go/go.sum

chore: update snappy
